export type Person = {
    pid: string;
    displayName: string;
    birthplace?: string;
    deathplace?: string;
    birthApprox?: boolean;
    deathApprox?: boolean;
    lat: number;
    lon: number;
    imageUrl: string;
    fromYear: number;
    fromApprox?: boolean;
    toYear: number;
    toApprox?: boolean;
    camps: string[];
    mainCamp?: string;
}

export const all_persons: Person[] = [
    {
        pid: "peter_the_apostle",
        displayName: "Peter the Apostle",
        birthplace: "Bethsaida, Galilee, Judaea, Roman Empire",
        deathplace: "Rome, Italia, Roman Empire",
        lat: 32.91089391890956,
        lon: 35.63200492242213,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Saint_Peter-Sinai_%286th_Century%29_Crop.jpg/1024px-Saint_Peter-Sinai_%286th_Century%29_Crop.jpg',
        fromYear: -1,
        fromApprox: true,
        toYear: 65,
        toApprox: true,
        camps: ["Apostle"]
    },
    {
        pid: "matthew_the_apostle",
        displayName: "Matthew the Apostle",
        birthplace: "Capernaum, Galilee, Judaea, Roman Empire",
        deathplace: "Ethiopia or Persia",
        lat: 32.88,
        lon: 35.57,
        imageUrl: 'https://i0.wp.com/www.thebestcatholic.com/wp-content/uploads/2016/09/The-Best-Catholic.Matthew5a319b0c116995afb26cab5af9e51e4c.wix_mp_1024.jpeg',
        fromYear: 4,
        fromApprox: true,
        toYear: 68,
        toApprox: true,
        camps: ["Apostle"]
    },
    {
        pid: "james_the_just",
        displayName: "James the Just",
        birthplace: "Nazareth, Galilee, Judaea, Roman Empire",
        deathplace: "Jerusalem, Judaea, Roman Empire",
        lat: 32.70234804256465,
        lon: 35.297873906995605,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/9/96/Saint_James_the_Just.jpg',
        fromYear: 4,
        fromApprox: true,
        toYear: 62,
        toApprox: true,
        camps: ["Apostle"]
    },
    {
        pid: "paul_of_tarsus",
        displayName: "Paul of Tarsus",
        birthplace: "Tarsus, Cilicia, Roman Empire",
        deathplace: "Rome, Italia, Roman Empire",
        lat: 36.92,
        lon: 34.90,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/7/79/Giovanni_Francesco_Barbieri_-_Saint_Paul.jpg/960px-Giovanni_Francesco_Barbieri_-_Saint_Paul.jpg?20190309231900',
        fromYear: 5,
        fromApprox: true,
        toYear: 65,
        toApprox: true,
        camps: ["Apostle"]
    },
    {
        pid: "john_the_apostle",
        displayName: "John the Apostle",
        birthplace: "Bethsaida, Galilee, Judaea, Roman Empire",
        deathplace: "Ephesus, Ionia, Asia Minor, Roman Empire",
        lat: 32.91089391890956,
        lon: 35.63200492242213,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/7/79/Rubens_apostel_johannes_grt.jpg/1024px-Rubens_apostel_johannes_grt.jpg',
        fromYear: 6,
        fromApprox: true,
        toYear: 100,
        toApprox: true,
        camps: ["Apostle"]
    },
    {
        pid: "john_mark_the_evangelist",
        displayName: "John Mark the Evangelist",
        birthplace: "Cyrene, Cyrenaica, Roman Empire",
        deathplace: "Alexandria, Egypt, Roman Empire",
        lat: 32.819808224773865,
        lon: 21.859442918983255,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/9/92/Frans_Hals_085.jpg/1024px-Frans_Hals_085.jpg',
        fromYear: 7,
        fromApprox: true,
        toYear: 68,
        toApprox: true,
        camps: ["Apostle"]
    },
    {
        pid: "luke_the_evangelist",
        displayName: "Luke the Evangelist",
        birthplace: "Antioch, Syria, Roman Empire",
        deathplace: "Thebes, Boeotia, Achaia, Roman Empire",
        lat: 36.20405931892094,
        lon: 36.16216594217945,
        imageUrl: 'https://images.weserv.nl/?url=myocn.net/wp-content/uploads/2019/10/St-Luke-2.jpeg',
        fromYear: 10,
        fromApprox: true,
        toYear: 94,
        toApprox: true,
        camps: ["Apostle"]
    },
    {
        pid: "judas_thaddaeus",
        displayName: "Judas Thaddaeus",
        birthplace: "Galilee, Judaea, Roman Empire",
        deathplace: "",
        lat: 32.69903106070133,
        lon: 35.303823054325235,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/0/0d/Anthonis_van_Dyck%2C_Kunsthistorisches_Museum_Wien%2C_Gem%C3%A4ldegalerie_-_Apostel_Judas_Thadd%C3%A4us_-_GG_6809_-_Kunsthistorisches_Museum.jpg',
        fromYear: 10,
        fromApprox: true,
        toYear: 65,
        toApprox: true,
        camps: ["Apostle"]
    },
    {
        pid: "simon_magus",
        displayName: "Simon Magus",
        birthplace: "Gitta, Samaria, Judaea, Roman Empire",
        deathplace: "Rome, Italia, Roman Empire",
        lat: 32.275,
        lon: 35.190,
        imageUrl: 'https://images.weserv.nl/?url=miro.medium.com/v2/1*dtSfizyQhZ6dAVIujqL6FA.jpeg',
        fromYear: 15,
        fromApprox: true,
        toYear: 65,
        toApprox: true,
        camps: ["Gnostic"]
    },
    {
        pid: "clement_of_rome",
        displayName: "Clement of Rome",
        birthplace: "Rome, Italia, Roman Empire",
        deathplace: "Chersonesus, Crimea, Bosporan Kingdom, Roman Empire",
        lat: 41.88,
        lon: 12.59,
        imageUrl: 'https://lonelypilgrim.com/wp-content/uploads/2014/05/clement-of-rome.jpg?w=214',
        fromYear: 35,
        fromApprox: true,
        toYear: 101,
        toApprox: true,
        camps: ["Apostolic Father"]
    },
    {
        pid: "ignatius_of_antioch",
        displayName: "Ignatius of Antioch",
        birthplace: "Syria, Roman Empire",
        deathplace: "Rome, Italia, Roman Empire",
        lat: 36.204930647486165,
        lon: 36.16699792842562,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/b/bf/Hosios_Loukas_%28south_west_chapel%2C_south_side%29_-_Ignatios.jpg',
        fromYear: 45,
        fromApprox: true,
        toYear: 116,
        toApprox: true,
        camps: ["Apostolic Father"]
    },
    {
        pid: "papias_of_hierapolis",
        displayName: "Papias of Hierapolis",
        lat: 37.91,
        lon: 29.11,
        imageUrl: 'https://pbcdn1.podbean.com/imglogo/ep-logo/pbblog17411067/papias.jpeg',
        fromYear: 60,
        fromApprox: true,
        toYear: 130,
        toApprox: true,
        camps: ["Apostolic Father"]
    },
    {
        pid: "polycarp_of_smyrna",
        displayName: "Polycarp of Smyrna",
        birthplace: "Smyrna, Asia Minor, Roman Empire",
        deathplace: "Smyrna, Asia Minor, Roman Empire",
        lat: 38.42270378420375,
        lon: 27.14573543165261,
        imageUrl: 'https://images.weserv.nl/?url=orthodoxwiki.org/images/4/41/Polycarp.jpg',
        fromYear: 69,
        fromApprox: true,
        toYear: 155,
        toApprox: true,
        camps: ["Apostolic Father"]
    },
    {
        pid: "marcion_of_sinope",
        displayName: "Marcion of Sinope",
        birthplace: "Sinope, Pontus, Roman Empire",
        deathplace: "Rome, Italia, Roman Empire",
        lat: 42.02723141456593,
        lon: 35.151250446989664,
        imageUrl: "",
        fromYear: 85,
        fromApprox: true,
        toYear: 160,
        toApprox: true,
        camps: ["Gnostic"]
    },
    {
        pid: "justin_martyr",
        displayName: "Justin Martyr",
        birthplace: "Flavius Neapolis, Judaea, Roman Empire",
        deathplace: "Rome, Italia, Roman Empire",
        lat: 32.22230610198572,
        lon: 35.25856314446059,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/a/a7/Saint_Justin_Martyr_by_Theophanes_the_Cretan.jpg',
        fromYear: 100,
        fromApprox: true,
        toYear: 165,
        toApprox: true,
        camps: ["Eastern Father"]
    },
    {
        pid: "valentinus_gnostic",
        displayName: "Valentinus",
        lat: 41.88,
        lon: 12.59,
        imageUrl: 'https://bpb-us-e1.wpmucdn.com/blogs.uoregon.edu/dist/7/10891/files/2015/05/valentinus-1kiu29x.jpg',
        fromYear: 100,
        fromApprox: true,
        toYear: 180,
        toApprox: true,
        camps: ["Gnostic"]
    },
    {
        pid: "irenaeus_of_lyon",
        displayName: "Irenaeus of Lyon",
        lat: 45.76,
        lon: 4.84,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/3/38/Saint_irenee_saint_irenee.jpg',
        fromYear: 125,
        fromApprox: true,
        toYear: 202,
        toApprox: true,
        camps: ["Western Father"]
    },
    {
        pid: "clement_of_alexandria",
        displayName: "Clement of Alexandria",
        birthplace: "Athens, Achaia, Roman Empire",
        deathplace: "Jerusalem, Syria Palaestina, Roman Empire",
        lat: 31.20025863903445,
        lon: 29.91846236548454,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Clement_alexandrin.jpg/500px-Clement_alexandrin.jpg',
        fromYear: 150,
        fromApprox: true,
        toYear: 215,
        toApprox: true,
        camps: ["Eastern Father"]
    },
    {
        pid: "tertullian_of_carthage",
        displayName: "Tertullian of Carthage",
        birthplace: "Carthage, Africa, Roman Empire",
        deathplace: "Carthage, Africa, Roman Empire",
        lat: 36.863945752812484,
        lon: 10.332574211900262,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/7/73/Tertullian2.png/1024px-Tertullian2.png',
        fromYear: 155,
        fromApprox: true,
        toYear: 220,
        toApprox: true,
        camps: ["Western Father", "Montanist"]
    },
    {
        pid: "hippolytus_of_rome",
        displayName: "Hippolytus of Rome",
        birthplace: "Rome, Italia, Roman Empire",
        deathplace: "Sardinia, Sardinia and Corsica, Roman Empire",
        lat: 41.88,
        lon: 12.59,
        imageUrl: 'https://images.weserv.nl/?url=images.oca.org/icons/lg/january/0130hippolytus.jpg',
        fromYear: 170,
        fromApprox: true,
        toYear: 236,
        toApprox: true,
        camps: ["Western Father"]
    },
    {
        pid: "alexander_of_jerusalem",
        displayName: "Alexander of Jerusalem",
        birthplace: "Unknown (Likely Cappadocia)",
        deathplace: "Caesarea Maritima, Syria Palaestina, Roman Empire",
        lat: 31.782201629960873,
        lon: 35.219051643225036,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/3/36/Alexander_of_Jerusalem.jpg',
        fromYear: 170,
        fromApprox: true,
        toYear: 251,
        toApprox: true,
        camps: ["Eastern Father"]
    },
    {
        pid: "origen_of_alexandria",
        displayName: "Origen of Alexandria",
        birthplace: "Alexandria, Egypt, Roman Empire",
        deathplace: "Tyre, Phoenice, Roman Empire",
        lat: 31.20025863903445,
        lon: 29.91846236548454,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/c/c7/Origen3.jpg',
        fromYear: 185,
        fromApprox: true,
        toYear: 253,
        toApprox: true,
        camps: ["Eastern Father", "Origenist"],
        mainCamp: "Origenist"
    },
    {
        pid: "cyprian_of_carthage",
        displayName: "Cyprian of Carthage",
        birthplace: "Carthage, Africa, Roman Empire",
        deathplace: "Carthage, Africa, Roman Empire",
        lat: 36.863945752812484,
        lon: 10.332574211900262,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/a/ae/Cyprian_von_Karthago2.jpg',
        fromYear: 210,
        fromApprox: true,
        toYear: 258,
        toApprox: true,
        camps: ["Western Father"]
    },
    {
        pid: "lucius_lactantius",
        displayName: "Lucius Lactantius",
        birthplace: "Unknown (Numidia)",
        deathplace: "Unknown",
        lat: 40.76770445285668,
        lon: 29.933262567556298,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/5/5c/Lactantius.jpg',
        fromYear: 250,
        fromApprox: true,
        toYear: 325,
        toApprox: true,
        camps: ["Western Father"]

    },
    {
        pid: "anthony_the_great",
        displayName: "Anthony the Great",
        birthplace: "Koma, Egypt, Roman Empire",
        deathplace: "Mount Colzim, Egypt, Roman Empire",
        lat: 29.299916177194383,
        lon: 31.169464033267953,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Saint_Anthony_%28Damaskinos%29.png/1024px-Saint_Anthony_%28Damaskinos%29.png',
        fromYear: 251,
        toYear: 356,
        camps: ["Eastern Father"]
    },
    {
        pid: "alexander_i_of_alexandria",
        displayName: "Alexander I of Alexandria",
        birthplace: "Unknown",
        deathplace: "Alexandria, Egypt, Roman Empire",
        lat: 31.20025863903445,
        lon: 29.91846236548454,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/e/ec/Veljusa_Monastery_St._Alexander_of_Alexandria.jpg',
        fromYear: 260,
        fromApprox: true,
        toYear: 328,
        toApprox: true,
        camps: ["Eastern Father", "Nicene"],
        mainCamp: "Nicene"
    },
    {
        pid: "eusebius_of_caesarea",
        displayName: "Eusebius of Caesarea",
        birthplace: "Caesarea Maritima, Syria Palaestina, Roman Empire",
        deathplace: "Caesarea Maritima, Syria Palaestina, Roman Empire",
        lat: 32.51667524676977,
        lon: 34.9019981388087,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/7/70/Eusebius_of_Caesarea_Rabbula_Gospels_Icon.jpg',
        fromYear: 260,
        fromApprox: true,
        toYear: 339,
        camps: ["Eastern Father", "Origenist"],
        mainCamp: "Origenist"
    },
    {
        pid: "athanasius_of_alexandria",
        displayName: "Athanasius of Alexandria",
        birthplace: "Alexandria, Egypt, Roman Empire",
        deathplace: "Alexandria, Egypt, Roman Empire",
        lat: 31.20025863903445,
        lon: 29.91846236548454,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/2/26/Ikone_Athanasius_von_Alexandria.jpg',
        fromYear: 296,
        fromApprox: true,
        toYear: 373,
        camps: ["Eastern Father", "Nicene"],
        mainCamp: "Nicene"

    },
    {
        pid: "epiphanius_of_salamis",
        displayName: "Epiphanius of Salamis",
        birthplace: "Besanduk, Syria Palaestina, Roman Empire",
        deathplace: "at sea near Cyprus",
        lat: 35.1865222055156,
        lon: 33.90346888919054,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/2/2c/Epiphanius-Kosovo.jpg',
        fromYear: 315,
        fromApprox: true,
        toYear: 403,
        camps: ["Eastern Father", "Nicene", "Iconoclast"],
        mainCamp: "Nicene"
    },
    {
        pid: "gregory_of_nazianzus",
        displayName: "Gregory of Nazianzus",
        birthplace: "Arianzus, Cappadocia, Roman Empire",
        deathplace: "Arianzus, Cappadocia, Roman Empire",
        lat: 38.26143964360644,
        lon: 34.38466113638501,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/5/5d/Gregor-Chora_%28cropped%29.jpg',
        fromYear: 329,
        fromApprox: true,
        toYear: 390,
        toApprox: true,
        camps: ["Eastern Father", "Nicene", "Cappadocian Father"],
        mainCamp: "Cappadocian Father"
    },
    {
        pid: "jerome_of_stridon",
        displayName: "Jerome of Stridon",
        birthplace: "Stridon, Dalmatia, Roman Empire",
        deathplace: "Bethlehem, Palaestina, Byzantine Empire",
        lat: 44.2,
        lon: 17.7,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/5/5f/MatthiasStom-SaintJerome-Nantes.jpg',
        fromYear: 342,
        fromApprox: true,
        toYear: 420,
        camps: ["Western Father", "Nicene"],
        mainCamp: "Nicene"
    },
    {
        pid: "rufinus_of_aquileia",
        displayName: "Rufinus of Aquileia",
        lat: 45.767206596249956,
        lon: 13.368906699413515,
        imageUrl: 'https://images.weserv.nl/?url=https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Rufinus_Aquileiensis.jpg/800px-Rufinus_Aquileiensis.jpg',
        fromYear: 344,
        fromApprox: true,
        toYear: 411,
        toApprox: true,
        camps: ["Western Father", "Origenist"],
        mainCamp: "Origenist"
    },
    {
        pid: "augustine_of_hippo",
        displayName: "Augustine of Hippo",
        lat: 36.90,
        lon: 7.75,
        imageUrl: 'https://images.fineartamerica.com/images/artworkimages/mediumlarge/3/saint-augustine-of-hippo-philippe-de-champaigne-war-is-hell-store.jpg',
        fromYear: 354,
        toYear: 430,
        camps: ["Western Father", "Nicene"],
        mainCamp: "Nicene"
    }
]