export type WorkEntry = {
    text: string;
    ital?: boolean;
    // Estimated date of composition, rendered after the title, e.g. "2nd cent. AD".
    // Expected on pseudepigrapha and associated works; on authentic or disputed
    // works only where there is clear consensus on the date.
    time?: string;
}

export type Person = {
    pid: string;
    displayName: string;
    altNames?: string[];
    birthplace?: string;
    deathplace?: string;
    lat: number;
    lon: number;
    imageUrl?: string;
    fromYear: number;
    fromApprox?: boolean;
    toYear: number;
    toApprox?: boolean;
    camps: string[];
    mainCamp?: string;
    authentic_works?: WorkEntry[];
    disputed_works?: WorkEntry[];
    pseudo_works?: WorkEntry[];
    // Works about the person rather than by or ascribed to them: biographies,
    // hagiography, rules, legends, institutional documents.
    works_about?: WorkEntry[];
}

export const all_persons: Person[] = [
    {
        pid: "peter_the_apostle",
        displayName: "Peter the Apostle",
        altNames: ["Simon Peter", "Cephas"],
        birthplace: "Bethsaida, Galilee, Roman Empire",
        deathplace: "Rome, Italia, Roman Empire",
        lat: 32.91089391890956,
        lon: 35.63200492242213,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Saint_Peter-Sinai_%286th_Century%29_Crop.jpg/1024px-Saint_Peter-Sinai_%286th_Century%29_Crop.jpg',
        fromYear: -1,
        fromApprox: true,
        toYear: 65,
        toApprox: true,
        camps: ["Apostle", "Greek"],
        authentic_works: [
            {text: "First Epistle of Peter", ital: true},
            {text: "Second Epistle of Peter", ital: true},
        ],
        pseudo_works: [
            {text: "Revelation of Peter", ital: true, time: "2nd cent. AD"},
        ],
        works_about: [
            {text: "Acts of Peter", ital: true, time: "2nd cent. AD"},
        ]
    },
    {
        pid: "matthew_the_apostle",
        displayName: "Matthew the Apostle",
        birthplace: "Capernaum, Galilee, Roman Empire",
        deathplace: "Unknown",
        lat: 32.88,
        lon: 35.57,
        imageUrl: 'https://i0.wp.com/www.thebestcatholic.com/wp-content/uploads/2016/09/The-Best-Catholic.Matthew5a319b0c116995afb26cab5af9e51e4c.wix_mp_1024.jpeg',
        fromYear: 4,
        fromApprox: true,
        toYear: 68,
        toApprox: true,
        camps: ["Apostle", "Greek"],
        authentic_works: [
            {text: "Gospel of Matthew", ital: true}
        ]
    },
    {
        pid: "james_the_just",
        displayName: "James the Just",
        birthplace: "Nazareth, Galilee, Roman Empire",
        deathplace: "Jerusalem, Judaea, Roman Empire",
        lat: 32.70234804256465,
        lon: 35.297873906995605,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/9/96/Saint_James_the_Just.jpg',
        fromYear: 4,
        fromApprox: true,
        toYear: 62,
        toApprox: true,
        camps: ["Apostle", "Greek"],
        authentic_works: [
            {text: "Epistle of James", ital: true}
        ],
    },
    {
        pid: "paul_of_tarsus",
        displayName: "Paul of Tarsus",
        birthplace: "Tarsus, Cilicia, Roman Empire",
        deathplace: "Rome, Italia, Roman Empire",
        lat: 36.92,
        lon: 34.90,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/7/79/Giovanni_Francesco_Barbieri_-_Saint_Paul.jpg/960px-Giovanni_Francesco_Barbieri_-_Saint_Paul.jpg?20190309231900',
        fromYear: 5,
        fromApprox: true,
        toYear: 65,
        toApprox: true,
        camps: ["Apostle", "Greek"],
        authentic_works: [
            {text: "Epistle to the Romans", ital: true},
            {text: "First Epistle to the Corinthians", ital: true},
            {text: "Second Epistle to the Corinthians", ital: true},
            {text: "Epistle to the Galatians", ital: true},
            {text: "Epistle to the Ephesians", ital: true},
            {text: "Epistle to the Philippians", ital: true},
            {text: "Epistle to the Colossians", ital: true},
            {text: "First Epistle to the Thessalonians", ital: true},
            {text: "Second Epistle to the Thessalonians", ital: true},
            {text: "First Epistle to Timothy", ital: true},
            {text: "Second Epistle to Timothy", ital: true},
            {text: "Epistle to Titus", ital: true},
            {text: "Epistle to Philemon", ital: true},
        ],
        disputed_works: [
            {text: "Epistle to the Hebrews", ital: true},
        ]
    },
    {
        pid: "john_the_apostle",
        displayName: "John the Apostle",
        birthplace: "Bethsaida, Galilee, Roman Empire",
        deathplace: "Ephesus, Asia, Roman Empire",
        lat: 32.91089391890956,
        lon: 35.63200492242213,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/7/79/Rubens_apostel_johannes_grt.jpg/1024px-Rubens_apostel_johannes_grt.jpg',
        fromYear: 6,
        fromApprox: true,
        toYear: 100,
        toApprox: true,
        camps: ["Apostle", "Greek"],
        authentic_works: [
            {text: "Gospel of John", ital: true}
        ],
        disputed_works: [
            {text: "First Epistle of John", ital: true},
            {text: "Second Epistle of John", ital: true},
            {text: "Third Epistle of John", ital: true},
            {text: "Revelation of John", ital: true}
        ]
    },
    {
        pid: "john_mark_the_evangelist",
        displayName: "John Mark the Evangelist",
        birthplace: "Cyrene, Cyrenaica, Roman Empire",
        deathplace: "Alexandria, Aegyptus, Roman Empire",
        lat: 32.819808224773865,
        lon: 21.859442918983255,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/9/92/Frans_Hals_085.jpg/1024px-Frans_Hals_085.jpg',
        fromYear: 7,
        fromApprox: true,
        toYear: 68,
        toApprox: true,
        camps: ["Apostle", "Greek"],
        authentic_works: [
            {text: "Gospel of Mark", ital: true}
        ],
    },
    {
        pid: "luke_the_evangelist",
        displayName: "Luke the Evangelist",
        birthplace: "Antioch, Syria, Roman Empire",
        deathplace: "Thebes, Achaia, Roman Empire",
        lat: 36.20405931892094,
        lon: 36.16216594217945,
        imageUrl: 'https://images.weserv.nl/?url=myocn.net/wp-content/uploads/2019/10/St-Luke-2.jpeg',
        fromYear: 10,
        fromApprox: true,
        toYear: 94,
        toApprox: true,
        camps: ["Apostle", "Greek"],
        authentic_works: [
            {text: "Gospel of Luke", ital: true},
            {text: "Acts of the Apostles", ital: true}
        ],
    },
    {
        pid: "judas_thaddaeus",
        displayName: "Judas Thaddaeus",
        birthplace: "Unknown, Galilee, Roman Empire",
        deathplace: "Berytus, Phoenice, Roman Empire",
        lat: 32.69903106070133,
        lon: 35.303823054325235,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/0/0d/Anthonis_van_Dyck%2C_Kunsthistorisches_Museum_Wien%2C_Gem%C3%A4ldegalerie_-_Apostel_Judas_Thadd%C3%A4us_-_GG_6809_-_Kunsthistorisches_Museum.jpg',
        fromYear: 10,
        fromApprox: true,
        toYear: 65,
        toApprox: true,
        camps: ["Apostle", "Greek"],
        authentic_works: [
            {text: "Epistle of Jude", ital: true}
        ],
    },
    {
        pid: "simon_magus",
        displayName: "Simon Magus",
        birthplace: "Gitta, Judaea, Roman Empire",
        deathplace: "Rome, Italia, Roman Empire",
        lat: 32.275,
        lon: 35.190,
        imageUrl: 'https://images.weserv.nl/?url=miro.medium.com/v2/1*dtSfizyQhZ6dAVIujqL6FA.jpeg',
        fromYear: 15,
        fromApprox: true,
        toYear: 65,
        toApprox: true,
        camps: ["Gnostic*", "Greek"],
        pseudo_works: [
            {text: "The Great Announcement", ital: true, time: "~2nd cent. AD"},
        ]
    },
    {
        pid: "clement_i_of_rome",
        displayName: "Clement I of Rome",
        birthplace: "Rome, Italia, Roman Empire",
        deathplace: "Chersonesus, Taurica, Roman Empire",
        lat: 41.88,
        lon: 12.59,
        imageUrl: 'https://lonelypilgrim.com/wp-content/uploads/2014/05/clement-of-rome.jpg?w=214',
        fromYear: 35,
        fromApprox: true,
        toYear: 101,
        toApprox: true,
        camps: ["Apostolic Father", "Greek"],
        authentic_works: [
            {text: "First Epistle of Clement to the Corinthians", ital: true}
        ],
        disputed_works: [
            {text: "Second Epistle of Clement to the Corinthians", ital: true}
        ]
    },
    {
        pid: "ignatius_of_antioch",
        displayName: "Ignatius of Antioch",
        birthplace: "Unknown, Syria, Roman Empire",
        deathplace: "Rome, Italia, Roman Empire",
        lat: 36.204930647486165,
        lon: 36.16699792842562,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/b/bf/Hosios_Loukas_%28south_west_chapel%2C_south_side%29_-_Ignatios.jpg',
        fromYear: 45,
        fromApprox: true,
        toYear: 116,
        toApprox: true,
        camps: ["Apostolic Father", "Greek"],
        authentic_works: [
            {text: "Epistle of Ignatius to the Ephesians", ital: true},
            {text: "Epistle of Ignatius to the Magnesians", ital: true},
            {text: "Epistle of Ignatius to the Trallians", ital: true},
            {text: "Epistle of Ignatius to the Romans", ital: true},
            {text: "Epistle of Ignatius to the Philadelphians", ital: true},
            {text: "Epistle of Ignatius to the Smyrnaeans", ital: true},
            {text: "Epistle of Ignatius to Polycarp", ital: true},
        ],
        pseudo_works: [
            {text: "Epistle of Ignatius to the Tarsians", ital: true, time: "4th cent. AD"},
            {text: "Epistle of Ignatius to the Antiochians", ital: true, time: "4th cent. AD"},
            {text: "Epistle of Ignatius to the Philippians", ital: true, time: "4th cent. AD"},
            {text: "Epistle of Ignatius to Hero", ital: true, time: "4th cent. AD"},
            {text: "Epistle of Ignatius to Mary of Cassobloa", ital: true, time: "4th cent. AD"},
            {text: "Epistle of Ignatius to the Virgin Mary", ital: true, time: "12th cent. AD"},
            {text: "First Epistle of Ignatius to John", ital: true, time: "12th cent. AD"},
            {text: "Second Epistle of Ignatius to John", ital: true, time: "12th cent. AD"},
        ],
        works_about: [
            {text: "Epistle of the Virgin Mary to Ignatius", ital: true, time: "12th cent. AD"},
        ]
    },
    {
        pid: "papias_of_hierapolis",
        displayName: "Papias of Hierapolis",
        birthplace: "Unknown, Phrygia, Roman Empire",
        deathplace: "Hierapolis, Phrygia, Roman Empire",
        lat: 37.91,
        lon: 29.11,
        imageUrl: 'https://pbcdn1.podbean.com/imglogo/ep-logo/pbblog17411067/papias.jpeg',
        fromYear: 60,
        fromApprox: true,
        toYear: 130,
        toApprox: true,
        camps: ["Apostolic Father", "Greek"],
        authentic_works: [
            {text: "Exposition of the Sayings of the Lord", ital: true},
        ]
    },
    {
        pid: "polycarp_of_smyrna",
        displayName: "Polycarp of Smyrna",
        birthplace: "Smyrna, Asia, Roman Empire",
        deathplace: "Smyrna, Asia, Roman Empire",
        lat: 38.42270378420375,
        lon: 27.14573543165261,
        imageUrl: 'https://images.weserv.nl/?url=https://i.pinimg.com/736x/36/95/1c/36951cf9601c961e123d0dfac021146e.jpg',
        fromYear: 69,
        fromApprox: true,
        toYear: 155,
        toApprox: true,
        camps: ["Apostolic Father", "Greek"],
        authentic_works: [
            {text: "Epistle of Polycarp to the Philippians", ital: true},
        ]
    },
    {
        pid: "marcion_of_sinope",
        displayName: "Marcion of Sinope",
        birthplace: "Sinope, Pontus, Roman Empire",
        deathplace: "Rome, Italia, Roman Empire",
        lat: 42.02723141456593,
        lon: 35.151250446989664,
        imageUrl: "",
        fromYear: 85,
        fromApprox: true,
        toYear: 160,
        toApprox: true,
        camps: ["Gnostic", "Greek"],
        authentic_works: [
            {text: "Antitheses", ital: true},
            {text: "Gospel of Marcion", ital: true},
        ]
    },
    {
        pid: "justin_martyr",
        displayName: "Justin Martyr",
        birthplace: "Flavius Neapolis, Judaea, Roman Empire",
        deathplace: "Rome, Italia, Roman Empire",
        lat: 32.22230610198572,
        lon: 35.25856314446059,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/a/a7/Saint_Justin_Martyr_by_Theophanes_the_Cretan.jpg',
        fromYear: 100,
        fromApprox: true,
        toYear: 165,
        toApprox: true,
        camps: ["Eastern Father", "Greek"],
        authentic_works: [
            {text: "First Apology", ital: true},
            {text: "Second Apology", ital: true},
            {text: "Dialogue with Trypho", ital: true},
        ],
        pseudo_works: [
            {text: "Discourse to the Greeks", ital: true, time: "~3rd cent. AD"},
            {text: "Exhortation to the Greeks", ital: true, time: "~3rd cent. AD"},
            {text: "On the Monarchy of God", ital: true, time: "~3rd cent. AD"},
        ]
    },
    {
        pid: "melito_of_sardis",
        displayName: "Melito of Sardis",
        altNames: ["Melito Sardianus", "Melito of Sardes", "Meliton Sardeon"],
        birthplace: "Sardis, Asia, Roman Empire",
        deathplace: "Sardis, Asia, Roman Empire",
        lat: 38.488300,
        lon: 28.040600,
        imageUrl: 'https://images.weserv.nl/?url=jonrodebaugh.wordpress.com/wp-content/uploads/2014/05/melito-of-sardis.jpg',
        fromYear: 100,
        fromApprox: true,
        toYear: 180,
        toApprox: true,
        camps: ["Eastern Father", "Greek"],
        authentic_works: [
            {text: "On the Pascha", ital: true},
            {text: "Apology to Marcus Aurelius", ital: true},
        ]
    },
    {
        pid: "valentinus_gnostic",
        displayName: "Valentinus",
        birthplace: "Phrebonis, Aegyptus, Roman Empire",
        deathplace: "Unknown, Cyprus, Roman Empire",
        lat: 41.88,
        lon: 12.59,
        imageUrl: '',
        fromYear: 100,
        fromApprox: true,
        toYear: 180,
        toApprox: true,
        camps: ["Gnostic", "Greek", "Coptic*"],
        disputed_works: [
            {text: "Gospel of Truth", ital: true},
        ]
    },
    {
        pid: "tatian_the_assyrian",
        displayName: "Tatian the Assyrian",
        altNames: ["Tatian the Syrian", "Tatian of Adiabene"],
        birthplace: "Unknown, Assyria, Parthian Empire",
        deathplace: "Unknown, Adiabene, Parthian Empire",
        lat: 35.453997,
        lon: 43.257500,
        imageUrl: "https://images.weserv.nl/?url=images.squarespace-cdn.com/content/59714ce0cd39c3d2d282cc58/1500693415502-KN0XEXF712GJ1QNXTBVQ/tatian.jpg?content-type=image%2Fjpeg",
        fromYear: 120,
        fromApprox: true,
        toYear: 180,
        toApprox: true,
        camps: ["Eastern Father", "Gnostic*", "Syriac", "Greek"],
        authentic_works: [
            {text: "Address to the Greeks", ital: true},
            {text: "Diatessaron", ital: true},
        ]
    },
    {
        pid: "theophilus_of_antioch",
        displayName: "Theophilus of Antioch",
        altNames: ["Theophilus of Antiochenus"],
        birthplace: "Unknown, Adiabene, Parthian Empire",
        deathplace: "Antioch, Syria, Roman Empire",
        lat: 36.20655,
        lon: 36.15722,
        imageUrl: "https://images.weserv.nl/?url=edenstree.weebly.com/uploads/1/3/8/7/13874379/762102926.jpg",
        fromYear: 120,
        fromApprox: true,
        toYear: 183,
        toApprox: true,
        camps: ["Eastern Father", "Greek"],
        authentic_works: [
            {text: "Apology to Autolycus", ital: true},
        ]
    },
    {
        pid: "irenaeus_of_lyon",
        displayName: "Irenaeus of Lyon",
        birthplace: "Smyrna, Asia, Roman Empire",
        deathplace: "Lugdunum, Gallia Lugdunensis, Roman Empire",
        lat: 45.76,
        lon: 4.84,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/3/38/Saint_irenee_saint_irenee.jpg',
        fromYear: 125,
        fromApprox: true,
        toYear: 202,
        toApprox: true,
        camps: ["Western Father", "Greek", "Latin*"],
        authentic_works: [
            {text: "Against Heresies", ital: true},
            {text: "Demonstration of the Apostolic Preaching", ital: true},
        ]
    },
    {
        pid: "athenagoras_of_athens",
        displayName: "Athenagoras of Athens",
        altNames: ["Athenagoras the Athenian"],
        birthplace: "Athens, Achaia, Roman Empire",
        deathplace: "Athens, Achaia, Roman Empire",
        lat: 37.9838,
        lon: 23.7275,
        imageUrl: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/6/62/Greek_Icon_of_Saint_Athenagoras_of_Athens.jpg/960px-Greek_Icon_of_Saint_Athenagoras_of_Athens.jpg",
        fromYear: 133,
        fromApprox: true,
        toYear: 190,
        toApprox: true,
        camps: ["Eastern Father", "Greek"],
        authentic_works: [
            {text: "A Plea for the Christians", ital: true},
        ],
        disputed_works: [
            {text: "On the Resurrection of the Dead", ital: true},
        ]
    },
    {
        pid: "clement_of_alexandria",
        displayName: "Clement of Alexandria",
        altNames: ["Titus Flavius Clemens"],
        birthplace: "Athens, Achaia, Roman Empire",
        deathplace: "Jerusalem, Syria Palaestina, Roman Empire",
        lat: 31.20025863903445,
        lon: 29.91846236548454,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Clement_alexandrin.jpg/500px-Clement_alexandrin.jpg',
        fromYear: 150,
        fromApprox: true,
        toYear: 215,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Alexandrian"],
        mainCamp: "Eastern Father",
        authentic_works: [
            {text: "Protrepticus", ital: true},
            {text: "Paedagogus", ital: true},
            {text: "Stromata", ital: true},
            {text: "Who is the Rich Man who is Saved?", ital: true},
        ],
        disputed_works: [
            {text: "Mar Saba letter", ital: false}
        ]
    },
    {
        pid: "tertullian_of_carthage",
        displayName: "Tertullian of Carthage",
        birthplace: "Carthage, Africa, Roman Empire",
        deathplace: "Carthage, Africa, Roman Empire",
        lat: 36.863945752812484,
        lon: 10.332574211900262,
        imageUrl: 'https://images.weserv.nl/?url=https://upload.wikimedia.org/wikipedia/commons/e/e9/Tertullian.jpg',
        fromYear: 155,
        fromApprox: true,
        toYear: 220,
        toApprox: true,
        camps: ["Western Father", "Latin", "Greek", "Montanist*"],
        authentic_works: [
            {text: "Apology", ital: true},
            {text: "Prescription Against Heretics", ital: true},
            {text: "Against Marcion", ital: true},
            {text: "Against the Valentinians", ital: true},
            {text: "Against Praxeas", ital: true},
            {text: "On the Soul", ital: true},
            {text: "On the Flesh of Christ", ital: true},
            {text: "On the Resurrection of the Flesh", ital: true},
            {text: "On Baptism", ital: true},
            {text: "On the Spectacles", ital: true},
            {text: "On Idolatry", ital: true},
            {text: "On the Dress of Women", ital: true},
            {text: "On the Veiling of Virgins", ital: true},
            {text: "On Flight in Persecution", ital: true},
            {text: "On Patience", ital: true},
            {text: "On Repentance", ital: true},
            {text: "On Modesty", ital: true},
            {text: "On Monogamy", ital: true},
            {text: "On Exhortation to Chastity", ital: true},
            {text: "On Fasting", ital: true},
            {text: "On Prayer", ital: true},
            {text: "Antidote for the Scorpion's Sting", ital: true},
            {text: "To His Wife", ital: true},
            {text: "To the Nations", ital: true},
            {text: "To Scapula", ital: true},
        ]
    },
    {
        pid: "hippolytus_of_rome",
        displayName: "Hippolytus of Rome",
        birthplace: "Rome, Italia, Roman Empire",
        deathplace: "Unknown, Sardinia et Corsica, Roman Empire",
        lat: 41.88,
        lon: 12.59,
        imageUrl: 'https://images.weserv.nl/?url=images.oca.org/icons/lg/january/0130hippolytus.jpg',
        fromYear: 170,
        fromApprox: true,
        toYear: 236,
        toApprox: true,
        camps: ["Western Father", "Greek"],
        authentic_works: [
            {text: "Refutation of All Heresies", ital: true},
            {text: "Commentary on Daniel", ital: true},
            {text: "On Christ and Antichrist", ital: true},
        ],
        disputed_works: [
            {text: "The Apostolic Tradition", ital: true},
        ]
    },
    {
        pid: "alexander_of_jerusalem",
        displayName: "Alexander of Jerusalem",
        altNames: ["Alexander of Cappadocia"],
        birthplace: "Unknown, Roman Empire",
        deathplace: "Caesarea Maritima, Syria Palaestina, Roman Empire",
        lat: 31.782201629960873,
        lon: 35.219051643225036,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/3/36/Alexander_of_Jerusalem.jpg',
        fromYear: 170,
        fromApprox: true,
        toYear: 251,
        toApprox: true,
        camps: ["Eastern Father", "Greek"],
        authentic_works: [
            {text: "Epistle of Alexander to the Antinoites", ital: true},
            {text: "Epistle of Alexander to the Antiochenes", ital: true},
            {text: "Epistle of Alexander to Origen", ital: true},
            {text: "Epistle of Alexander to Demetrius", ital: true},

        ]
    },
    {
        pid: "origen_of_alexandria",
        displayName: "Origen of Alexandria",
        birthplace: "Alexandria, Aegyptus, Roman Empire",
        deathplace: "Tyre, Phoenice, Roman Empire",
        lat: 31.20025863903445,
        lon: 29.91846236548454,
        imageUrl: 'https://images.weserv.nl/?url=//upload.wikimedia.org/wikipedia/commons/thumb/2/20/Origen.jpg/960px-Origen.jpg',
        fromYear: 185,
        fromApprox: true,
        toYear: 253,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Latin*", "Alexandrian", "Origenist"],
        mainCamp: "Origenist",
        authentic_works: [
            {text: "On the First Principles", ital: true},
            {text: "Against Celsus", ital: true},
            {text: "Hexapla", ital: true},
            {text: "Commentary on Matthew", ital: true},
            {text: "Commentary on John", ital: true},
            {text: "Commentary on Romans", ital: true},
            {text: "Commentary on Genesis", ital: true},
            {text: "Commentary on Song of Songs", ital: true},
            {text: "Commentary on Psalms", ital: true},
            {text: "Many Homilies", ital: false},
        ]
    },
    {
        pid: "cyprian_of_carthage",
        displayName: "Cyprian of Carthage",
        birthplace: "Carthage, Africa, Roman Empire",
        deathplace: "Carthage, Africa, Roman Empire",
        lat: 36.863945752812484,
        lon: 10.332574211900262,
        imageUrl: 'https://images.weserv.nl/?url=https://hcscchurch.org/wp-content/uploads/2013/09/Screen-Shot-2013-09-16-at-8.17.22-PM.png',
        fromYear: 210,
        fromApprox: true,
        toYear: 258,
        toApprox: true,
        camps: ["Western Father", "Latin"],
        authentic_works: [
            {text: "On the Unity of the Church", ital: true},
            {text: "On the Lapsed", ital: true},
            {text: "On the Dress of Virgins", ital: true},
        ]
    },
    {
        pid: "paul_of_thebes",
        displayName: "Paul of Thebes",
        birthplace: "Unknown, Aegyptus, Roman Empire",
        deathplace: "Thebes, Aegyptus, Roman Empire",
        lat: 25.713133070514296,
        lon: 32.62190391281979,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/3/39/Paul_of_Thebes.jpg',
        fromYear: 227,
        fromApprox: true,
        toYear: 341,
        toApprox: true,
        camps: ["Eastern Father", "Coptic", "Monastic"],
        mainCamp: "Monastic"
    },
    {
        pid: "lucius_lactantius",
        displayName: "Lucius Lactantius",
        birthplace: "Cirta, Numidia, Roman Empire",
        deathplace: "Augusta Treverorum, Gallia Belgica, Roman Empire",
        lat: 40.76770445285668,
        lon: 29.933262567556298,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/5/5c/Lactantius.jpg',
        fromYear: 250,
        fromApprox: true,
        toYear: 325,
        toApprox: true,
        camps: ["Western Father", "Latin"],
        authentic_works: [
            {text: "Divine Institutes", ital: true},
            {text: "On the Deaths of the Persecutors", ital: true},
            {text: "On the Workmanship of God", ital: true},
            {text: "On the Wrath of God", ital: true},
        ]

    },
    {
        pid: "anthony_the_great",
        displayName: "Anthony the Great",
        birthplace: "Koma, Aegyptus, Roman Empire",
        deathplace: "Mount Colzim, Aegyptus, Roman Empire",
        lat: 29.299916177194383,
        lon: 31.169464033267953,
        imageUrl: 'https://images.weserv.nl/?url=https://images.oca.org/icons/sm/january/0117anthony.jpg',
        fromYear: 251,
        toYear: 356,
        camps: ["Eastern Father", "Coptic", "Greek*", "Monastic"],
        mainCamp: "Monastic",
        authentic_works: [
            {text: "Letters of Saint Anthony", ital: true},
        ]
    },
    {
        pid: "hosius_of_cordoba",
        displayName: "Hosius of Cordoba",
        altNames: ["Hosius the Confessor", "Osius", "Ossius"],
        birthplace: "Cordoba, Hispania, Roman Empire",
        deathplace: "Cordoba, Hispania, Roman Empire",
        lat: 37.88923549620351,
        lon: -4.779505534652193,
        imageUrl: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/0/05/Hosius_of_Cordoba.jpg/250px-Hosius_of_Cordoba.jpg",
        fromYear: 256,
        fromApprox: true,
        toYear: 359,
        toApprox: true,
        camps: ["Western Father", "Latin", "Nicene"],
        mainCamp: "Nicene",
        authentic_works: [
            {text: "Letter to Constantius II", ital: true},
        ]
    },
    {
        pid: "arius_of_alexandria",
        displayName: "Arius of Alexandria",
        birthplace: "Ptolemais, Cyrenaica, Roman Empire",
        deathplace: "Constantinople, Thrace, Roman Empire",
        lat: 31.20025863903445,
        lon: 29.91846236548454,
        imageUrl: 'https://images.weserv.nl/?url=https://cdn.britannica.com/94/271794-050-E611A266/Arius-Alexandria-engraving-Christian-priest-Arianism.jpg',
        fromYear: 256,
        fromApprox: true,
        toYear: 336,
        camps: ["Eastern Father", "Greek", "Arian", "Alexandrian"],
        mainCamp: "Arian",
        authentic_works: [
            {text: "Thalia", ital: true},
            {text: "Letter to Eusebius of Nicomedia", ital: true},
            {text: "Letter to Alexander of Alexandria", ital: true},
        ]
    },
    {
        pid: "gregory_the_illuminator",
        displayName: "Gregory the Illuminator",
        altNames: ["Gregory the Enlightener", "Grigor Lusavorich", "Gregory I of Armenia"],
        birthplace: "Vagharshapat, Ayrarat, Kingdom of Armenia",
        deathplace: "Mount Sepuh, Daranali, Kingdom of Armenia",
        lat: 39.8786,
        lon: 44.5766,
        imageUrl: 'https://images.weserv.nl/?url=https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Gregory_the_Illuminator_Aghtamar_bas_relief.jpg/500px-Gregory_the_Illuminator_Aghtamar_bas_relief.jpg',
        fromYear: 257,
        fromApprox: true,
        toYear: 331,
        toApprox: true,
        camps: ["Eastern Father", "Greek"],
    },
    {
        pid: "alexander_i_of_alexandria",
        displayName: "Alexander I of Alexandria",
        birthplace: "Unknown, Roman Empire",
        deathplace: "Alexandria, Aegyptus, Roman Empire",
        lat: 31.20025863903445,
        lon: 29.91846236548454,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/e/ec/Veljusa_Monastery_St._Alexander_of_Alexandria.jpg',
        fromYear: 260,
        fromApprox: true,
        toYear: 328,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Nicene", "Alexandrian"],
        mainCamp: "Nicene"
    },
    {
        pid: "jacob_of_nisibis",
        displayName: "Jacob of Nisibis",
        altNames: ["James of Nisibis", "Jacob the Great", "James the Great", "Jacob of Mygdonia"],
        birthplace: "Nisibis, Mesopotamia, Roman Empire",
        deathplace: "Nisibis, Mesopotamia, Roman Empire",
        lat: 37.0750,
        lon: 41.2189,
        imageUrl: 'https://images.weserv.nl/?url=https://cdn11.bigcommerce.com/s-30c33/images/stencil/1280x1280/products/3643/5536/SaintJacobNisibisSmall__45369.1642617287.jpg?c=2',
        fromYear: 260,
        fromApprox: true,
        toYear: 338,
        toApprox: true,
        camps: ["Eastern Father", "Syriac", "Nicene", "Monastic"],
        mainCamp: "Monastic"
    },
    {
        pid: "eusebius_of_caesarea",
        displayName: "Eusebius of Caesarea",
        altNames: ["Eusebius Pamphilius"],
        birthplace: "Caesarea Maritima, Syria Palaestina, Roman Empire",
        deathplace: "Caesarea Maritima, Syria Palaestina, Roman Empire",
        lat: 32.51667524676977,
        lon: 34.9019981388087,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/7/70/Eusebius_of_Caesarea_Rabbula_Gospels_Icon.jpg',
        fromYear: 260,
        fromApprox: true,
        toYear: 339,
        camps: ["Eastern Father", "Greek", "Origenist"],
        mainCamp: "Origenist"
    },
    {
        pid: "eustathius_of_antioch",
        displayName: "Eustathius of Antioch",
        altNames: ["Eustathius the Great", "Eustathius of Side", "Eustathios of Antioch"],
        birthplace: "Side, Pamphylia, Roman Empire",
        deathplace: "Trajanopolis, Thrace, Roman Empire",
        lat: 36.2021,
        lon: 36.1613,
        imageUrl: 'https://images.weserv.nl/?url=https://blogger.googleusercontent.com/img/a/AVvXsEjtuJCotPNn9FxS2syjzkVk8geuJQrapwFjX6vg9om84JuKgP0mgCiAr5zy65yBg9yy0-fqoKpCw8mEJOuRWONrg18vJC_dO9QQ8pvRxhO11fMjRoRyw2g-x1AHYz_9qeDwHPhAx4j9eoCmSTwOFAWROkrEszSS8-x5wsIzelbA3KtthmVx2YDjkGp1Hw=w344-h400',
        fromYear: 270,
        fromApprox: true,
        toYear: 337,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Antiochene", "Nicene"],
        mainCamp: "Nicene"
    },
    {
        pid: "eusebius_of_nicomedia",
        displayName: "Eusebius of Nicomedia",
        birthplace: "Unknown, Roman Empire",
        deathplace: "Constantinople, Thrace, Roman Empire",
        lat: 40.76247630958466,
        lon: 29.917517499562084,
        imageUrl: '',
        fromYear: 280,
        fromApprox: true,
        toYear: 341,
        camps: ["Eastern Father", "Greek", "Arian"],
        mainCamp: "Arian"
    },
    {
        pid: "hilarion_of_gaza",
        displayName: "Hilarion of Gaza",
        altNames: ["Hilarion the Great", "Hilarion of Thavata"],
        birthplace: "Thavata, Syria Palaestina, Roman Empire",
        deathplace: "Unknown, Cyprus, Roman Empire",
        lat: 31.516648470299234,
        lon: 34.44998533044062,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/9/9f/Hilarion_the_Great_%28Menologion_of_Basil_II%29_%28cropped%29.jpg',
        fromYear: 291,
        fromApprox: true,
        toYear: 371,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Monastic"],
        mainCamp: "Monastic"
    },
    {
        pid: "pachomius_the_great",
        displayName: "Pachomius the Great",
        altNames: ["Pachomius of Tabennisi", "Pachomius the Elder"],
        birthplace: "Latopolis, Thebaid, Roman Empire",
        deathplace: "Pbow, Thebaid, Roman Empire",
        lat: 26.0522,
        lon: 32.2419,
        imageUrl: 'https://images.weserv.nl/?url=https://www.antiochpatriarchate.org/images/Saints/6283b9d3acc6ab071571e4859f6f37e6.jpg',
        fromYear: 292,
        fromApprox: true,
        toYear: 348,
        toApprox: false,
        camps: ["Eastern Father", "Coptic", "Latin*", "Nicene", "Monastic"],
        mainCamp: "Monastic"
    },
    {
        pid: "athanasius_of_alexandria",
        displayName: "Athanasius of Alexandria",
        birthplace: "Alexandria, Aegyptus, Roman Empire",
        deathplace: "Alexandria, Aegyptus, Roman Empire",
        lat: 31.20025863903445,
        lon: 29.91846236548454,
        imageUrl: 'https://images.weserv.nl/?url=https://stjohngoc.org/wp-content/uploads/2018/06/athanasius-the-great.jpg',
        fromYear: 296,
        fromApprox: true,
        toYear: 373,
        camps: ["Eastern Father", "Greek", "Nicene", "Alexandrian"],
        mainCamp: "Nicene"
    },
    {
        pid: "frumentius_of_axum",
        displayName: "Frumentius of Axum",
        birthplace: "Tyre, Phoenicia, Roman Empire",
        deathplace: "Aksum, Kingdom of Aksum",
        lat: 14.1211,
        lon: 38.7234,
        imageUrl: 'https://images.weserv.nl/?url=https://upload.wikimedia.org/wikipedia/commons/4/47/St_Frumentius.jpg',
        fromYear: 300,
        fromApprox: true,
        toYear: 383,
        toApprox: true,
        camps: ["Eastern Father", "Greek"]
    },
    {
        pid: "macarius_of_egypt",
        displayName: "Macarius of Egypt",
        altNames: ["Macarius the Great", "Macarius the Elder", "Macarius of Scetis"],
        birthplace: "Ptinapor, Aegyptus, Roman Empire",
        deathplace: "Scetis, Aegyptus, Roman Empire",
        lat: 30.3400,
        lon: 30.2800,
        imageUrl: 'https://images.weserv.nl/?url=https://cdn.thecollector.com/wp-content/uploads/2023/01/icon-of-saint-macarius.jpg?width=622&quality=100&dpr=2',
        fromYear: 300,
        fromApprox: true,
        toYear: 391,
        toApprox: true,
        camps: ["Eastern Father", "Coptic", "Greek*", "Nicene", "Monastic"],
        mainCamp: "Monastic"
    },
    {
        pid: "ephrem_the_syrian",
        displayName: "Ephrem the Syrian",
        altNames: ["Ephrem of Nisibis", "Ephrem of Edessa", "Ephraem the Syrian", "Ephraim the Syrian"],
        birthplace: "Nisibis, Mesopotamia, Roman Empire",
        deathplace: "Edessa, Osrhoene, Roman Empire",
        lat: 37.1591,
        lon: 38.7969,
        imageUrl: 'https://images.weserv.nl/?url=https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlEo5H6YyujAkd6fJw3oJy0Nl3vIUu_owOCBPdRry7QT5eX0bE9RvnElg&s=10',
        fromYear: 306,
        fromApprox: true,
        toYear: 373,
        toApprox: false,
        camps: ["Eastern Father", "Syriac", "Nicene", "Monastic"],
        mainCamp: "Nicene"
    },
    {
        pid: "hilary_of_poitiers",
        displayName: "Hilary of Poitiers",
        birthplace: "Pictavium, Gallia Aquitania, Roman Empire",
        deathplace: "Pictavium, Septem Provinciae, Roman Empire",
        lat: 46.579841096591224,
        lon: 0.3416894346137863,
        imageUrl: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjC7F2D82FrhL_0Sd2jA2xR3kQc3HgT-HMpdWMW9puaOAepVQtwemTYOBaL4RCN518M2S1yoIWK2-FOG94LZGtXtSwxPz3VqBjXM_McSba6_FUYdjIxPkyMoaY6zG2yOuNA_9QieZNlZTI/s512/hilary.jpg',
        fromYear: 310,
        fromApprox: true,
        toYear: 367,
        toApprox: true,
        camps: ["Western Father", "Latin", "Nicene"],
        mainCamp: "Nicene"
    },
    {
        pid: "didymus_the_blind",
        displayName: "Didymus the Blind",
        birthplace: "Alexandria, Aegyptus, Roman Empire",
        deathplace: "Alexandria, Aegyptus, Eastern Roman Empire",
        lat: 31.20025863903445,
        lon: 29.91846236548454,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/4/46/Didymus_the_blind.jpg',
        fromYear: 313,
        fromApprox: true,
        toYear: 398,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Alexandrian", "Origenist", "Nicene"],
        mainCamp: "Origenist"
    },
    {
        pid: "cyril_of_jerusalem",
        displayName: "Cyril of Jerusalem",
        altNames: ["Cyrillus Hierosolymitanus"],
        birthplace: "Jerusalem, Syria Palaestina, Roman Empire",
        deathplace: "Jerusalem, Palaestina Prima, Roman Empire",
        lat: 31.77889,
        lon: 35.22556,
        imageUrl: 'https://images.weserv.nl/?url=adoremus.org/app/uploads/2020/03/StCyril-5.jpg',
        fromYear: 315,
        fromApprox: true,
        toYear: 386,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Nicene"],
        mainCamp: "Nicene"
    },
    {
        pid: "epiphanius_of_salamis",
        displayName: "Epiphanius of Salamis",
        birthplace: "Besanduk, Syria Palaestina, Roman Empire",
        deathplace: "At sea near Cyprus, Eastern Roman Empire",
        lat: 35.1865222055156,
        lon: 33.90346888919054,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/2/2c/Epiphanius-Kosovo.jpg',
        fromYear: 315,
        fromApprox: true,
        toYear: 403,
        camps: ["Eastern Father", "Greek", "Nicene"],
        mainCamp: "Nicene"
    },
    {
        pid: "gregory_of_nazianzus",
        displayName: "Gregory of Nazianzus",
        altNames: ["Gregory Nazianzen"],
        birthplace: "Arianzus, Cappadocia, Roman Empire",
        deathplace: "Arianzus, Cappadocia, Roman Empire",
        lat: 38.26143964360644,
        lon: 34.38466113638501,
        imageUrl: 'https://images.weserv.nl/?url=https://www.saintgregorythetheologian.org/assets/images/st-gregory-the-theologian-julia-bridget-hayes.jpg',
        fromYear: 329,
        fromApprox: true,
        toYear: 390,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Nicene", "Cappadocian Father"],
        mainCamp: "Cappadocian Father"
    },
    {
        pid: "basil_of_caesarea",
        displayName: "Basil of Caesarea",
        altNames: ["Basil the Great"],
        birthplace: "Caesarea Mazaca, Cappadocia, Roman Empire",
        deathplace: "Caesarea Mazaca, Cappadocia, Roman Empire",
        lat: 38.722417611256404,
        lon: 35.48746598237236,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/0/04/Basil_of_Caesarea.jpg',
        fromYear: 330,
        fromApprox: true,
        toYear: 379,
        camps: ["Eastern Father", "Greek", "Nicene", "Cappadocian Father", "Monastic"],
        mainCamp: "Cappadocian Father"
    },
    {
        pid: "diodore_of_tarsus",
        displayName: "Diodore of Tarsus",
        altNames: ["Diodorus of Tarsus", "Diodorus Tarsensis"],
        birthplace: "Antioch, Coele Syria, Roman Empire",
        deathplace: "Tarsus, Cilicia Prima, Roman Empire",
        lat: 36.917700,
        lon: 34.892800,
        imageUrl: '',
        fromYear: 330,
        fromApprox: true,
        toYear: 394,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Syriac*", "Nicene", "Antiochene", "Monastic"],
        mainCamp: "Nicene",
    },
    {
        pid: "gregory_of_nyssa",
        displayName: "Gregory of Nyssa",
        altNames: ["Gregory Nyssen"],
        birthplace: "Neocaesarea, Cappadocia, Roman Empire",
        deathplace: "Nyssa, Cappadocia, Roman Empire",
        lat: 38.93386362845272,
        lon: 33.94907023316791,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/2/29/Gregory_of_Nyssa.jpg',
        fromYear: 335,
        fromApprox: true,
        toYear: 394,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Nicene", "Cappadocian Father", "Origenist*"],
        mainCamp: "Cappadocian Father"
    },
    {
        pid: "martin_of_tours",
        displayName: "Martin of Tours",
        altNames: ["Martin the Merciful", "Martinus Turonensis"],
        birthplace: "Savaria, Pannonia Prima, Roman Empire",
        deathplace: "Candes, Lugdunensis Tertia, Western Roman Empire",
        lat: 47.393611,
        lon: 0.682778,
        imageUrl: 'https://images.weserv.nl/?url=https://upload.wikimedia.org/wikipedia/commons/c/ce/Simone_Martini_040.jpg?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original',
        fromYear: 336,
        fromApprox: true,
        toYear: 397,
        toApprox: false,
        camps: ["Western Father", "Latin", "Nicene", "Monastic"],
        mainCamp: "Monastic"
    },
    {
        pid: "ambrose_of_milan",
        displayName: "Ambrose of Milan",
        altNames: ["Aurelius Ambrosius"],
        birthplace: "Augusta Treverorum, Belgica Prima, Roman Empire",
        deathplace: "Mediolanum, Liguria, Western Roman Empire",
        lat: 45.46509212922207,
        lon: 9.18057778962911,
        imageUrl: 'https://images.weserv.nl/?url=i.pinimg.com/736x/9d/63/52/9d6352be8f5cecf4f982ea7a014c31ee.jpg',
        fromYear: 339,
        fromApprox: true,
        toYear: 397,
        camps: ["Western Father", "Latin", "Nicene"],
        mainCamp: "Nicene"
    },
    {
        pid: "jerome_of_stridon",
        displayName: "Jerome of Stridon",
        birthplace: "Stridon, Dalmatia, Roman Empire",
        deathplace: "Bethlehem, Palaestina, Eastern Roman Empire",
        lat: 44.2,
        lon: 17.7,
        imageUrl: 'https://images.weserv.nl/?url=cdn.britannica.com/06/234006-050-DA86F56B/Saint-Jerome-by-Jose-de-Ribera-c1638-1640.jpg',
        fromYear: 342,
        fromApprox: true,
        toYear: 420,
        camps: ["Western Father", "Eastern Father", "Latin", "Greek", "Nicene", "Monastic"],
        mainCamp: "Nicene"
    },
    {
        pid: "rufinus_of_aquileia",
        displayName: "Rufinus of Aquileia",
        birthplace: "Concordia, Venetia et Histria, Roman Empire",
        deathplace: "Unknown, Sicilia, Western Roman Empire",
        lat: 45.767206596249956,
        lon: 13.368906699413515,
        imageUrl: 'https://images.weserv.nl/?url=https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Rufinus_Aquileiensis.jpg/960px-Rufinus_Aquileiensis.jpg',
        fromYear: 344,
        fromApprox: true,
        toYear: 411,
        toApprox: true,
        camps: ["Western Father", "Latin", "Greek", "Origenist"],
        mainCamp: "Origenist"
    },
    {
        pid: "evagrius_ponticus",
        displayName: "Evagrius Ponticus",
        altNames: ["Evagrius of Pontus", "Evagrius the Solitary", "Euagrios Pontikos"],
        birthplace: "Ibora, Helenopontus, Roman Empire",
        deathplace: "Kellia, Aegyptus, Eastern Roman Empire",
        lat: 30.776003,
        lon: 30.368868,
        imageUrl: 'https://images.weserv.nl/?url=firstthoughtsofgod.com/wp-content/uploads/2023/04/evagrius-edited.jpg',
        fromYear: 345,
        fromApprox: true,
        toYear: 399,
        camps: ["Eastern Father", "Greek", "Syriac*", "Nicene", "Origenist", "Monastic"],
        mainCamp: "Origenist",
    },
    {
        pid: "john_chrysostom",
        displayName: "John Chrysostom",
        altNames: ["John of Antioch", "John of Constantinople"],
        birthplace: "Antioch, Coele Syria, Roman Empire",
        deathplace: "Comana Pontica, Helenopontus, Eastern Roman Empire",
        lat: 41.00817513927148,
        lon: 28.978539039041394,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/c/cf/Johnchrysostom.jpg',
        fromYear: 349,
        fromApprox: true,
        toYear: 407,
        camps: ["Eastern Father", "Greek", "Nicene", "Antiochene"],
        mainCamp: "Nicene"
    },
    {
        pid: "theodore_ii_of_mopsuestia",
        displayName: "Theodore II of Mopsuestia",
        altNames: ["Theodore of Antioch", "Theodore of Mopsuestia", "Theodorus Mopsuestenus"],
        birthplace: "Antioch, Coele Syria, Roman Empire",
        deathplace: "Mopsuestia, Cilicia Secunda, Eastern Roman Empire",
        lat: 36.96049355024225,
        lon: 35.625092916861384,
        imageUrl: '',
        fromYear: 350,
        fromApprox: true,
        toYear: 428,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Syriac*", "Nicene", "Antiochene", "Monastic"],
        mainCamp: "Antiochene",
    },
    {
        pid: "pelagius_pelagian",
        displayName: "Pelagius",
        altNames: ["Pelagius the Monk", "Pelagius Brito"],
        birthplace: "Unknown, Britannia, Roman Empire",
        deathplace: "Unknown",
        lat: 52.4153,
        lon: -3.4821,
        imageUrl: 'https://images.weserv.nl/?url=https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Pelagius.jpg/960px-Pelagius.jpg',
        fromYear: 354,
        fromApprox: true,
        toYear: 418,
        toApprox: true,
        camps: ["Western Father", "Latin", "Pelagian", "Monastic"],
        mainCamp: "Pelagian"
    },
    {
        pid: "augustine_of_hippo",
        displayName: "Augustine of Hippo",
        altNames: ["Aurelius Augustinus", "Austin"],
        birthplace: "Thagaste, Numidia Cirtensis, Roman Empire",
        deathplace: "Hippo Regius, Numidia Cirtensis, Western Roman Empire",
        lat: 36.90,
        lon: 7.75,
        imageUrl: 'https://images.fineartamerica.com/images/artworkimages/mediumlarge/3/saint-augustine-of-hippo-philippe-de-champaigne-war-is-hell-store.jpg',
        fromYear: 354,
        toYear: 430,
        camps: ["Western Father", "Latin", "Nicene", "Augustinian", "Monastic"],
        mainCamp: "Augustinian"
    },
    {
        pid: "celestine_i_of_rome",
        displayName: "Celestine I of Rome",
        altNames: ["Pope Celestine I", "Celestinus I"],
        birthplace: "Unknown, Campania, Roman Empire",
        deathplace: "Rome, Campania, Western Roman Empire",
        lat: 41.9028,
        lon: 12.4964,
        imageUrl: 'https://images.weserv.nl/?url=https://upload.wikimedia.org/wikipedia/commons/1/12/Dundalk_Saint_Patrick%27s_Pro-Cathedral_West_Aisle_Window_06_Lower_Lights_2013_09_23%28cropped%29.jpg',
        fromYear: 359,
        fromApprox: true,
        toYear: 432,
        toApprox: false,
        camps: ["Western Father", "Latin", "Nicene", "Alexandrian", "Augustinian"],
        mainCamp: "Nicene"
    },
    {
        pid: "john_cassian",
        displayName: "John Cassian",
        altNames: ["John the Ascetic", "John Cassian the Roman"],
        birthplace: "Unknown, Scythia Minor, Roman Empire",
        deathplace: "Massalia, Gallia Narbonensis, Western Roman Empire",
        lat: 43.30270514648704,
        lon: 5.36823823706311,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/a/a0/John_Cassian.jpeg/960px-John_Cassian.jpeg',
        fromYear: 360,
        fromApprox: true,
        toYear: 435,
        toApprox: true,
        camps: ["Western Father", "Eastern Father", "Latin", "Greek", "Nicene", "Massilian", "Monastic"],
        mainCamp: "Massilian"
    },
    {
        pid: "isidore_of_pelusium",
        displayName: "Isidore of Pelusium",
        altNames: ["Isidore Pelusiota", "Isidorus Pelusiota"],
        birthplace: "Alexandria, Aegyptus, Roman Empire",
        deathplace: "Pelusium, Augustamnica Prima, Eastern Roman Empire",
        lat: 31.041900,
        lon: 32.545300,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/1/13/Isidore_of_Pelusium.jpg',
        fromYear: 360,
        fromApprox: true,
        toYear: 449,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Nicene", "Monastic"],
        mainCamp: "Monastic",
    },
    {
        pid: "john_i_of_antioch",
        displayName: "John I of Antioch",
        altNames: ["John of Antioch", "John, Patriarch of Antioch"],
        birthplace: "Antioch, Coele Syria, Roman Empire",
        deathplace: "Antioch, Syria Prima, Eastern Roman Empire",
        lat: 36.202105,
        lon: 36.160509,
        imageUrl: '',
        fromYear: 370,
        fromApprox: true,
        toYear: 441,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Antiochene"],
        mainCamp: "Antiochene",
    },
    {
        pid: "cyril_of_alexandria",
        displayName: "Cyril of Alexandria",
        altNames: ["Cyrillus Alexandrinus"],
        birthplace: "Didouseya, Aegyptus, Roman Empire",
        deathplace: "Alexandria, Aegyptus, Eastern Roman Empire",
        lat: 31.200100,
        lon: 29.918700,
        imageUrl: 'https://images.weserv.nl/?url=russianorthodoxchurchcardiff.com/wp-content/uploads/2023/06/02908D49-6621-4A95-A33A-C48D8048EE91.jpeg',
        fromYear: 375,
        fromApprox: true,
        toYear: 444,
        toApprox: false,
        camps: ["Eastern Father", "Greek", "Nicene", "Alexandrian"],
        mainCamp: "Alexandrian",
    },
    {
        pid: "eutyches_of_constantinople",
        displayName: "Eutyches of Constantinople",
        altNames: ["Archimandrite Eutyches"],
        birthplace: "Constantinople, Thrace, Roman Empire",
        deathplace: "Unknown, Eastern Roman Empire",
        lat: 41.0082,
        lon: 28.9784,
        imageUrl: 'https://images.weserv.nl/?url=https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Portret_van_Eutyches._NL-HlmNHA_53008820.JPG/960px-Portret_van_Eutyches._NL-HlmNHA_53008820.JPG',
        fromYear: 378,
        fromApprox: true,
        toYear: 454,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Alexandrian", "Miaphysite", "Eutychian*"],
        mainCamp: "Eutychian*"
    },
    {
        pid: "caelestius_pelagian",
        displayName: "Caelestius",
        altNames: ["Celestius"],
        birthplace: "Unknown, Roman Empire",
        deathplace: "Unknown, Eastern Roman Empire",
        lat: 41.9028,
        lon: 12.4964,
        imageUrl: '',
        fromYear: 380,
        fromApprox: true,
        toYear: 430,
        toApprox: true,
        camps: ["Western Father", "Latin", "Pelagian"],
        mainCamp: "Pelagian"
    },
    {
        pid: "proclus_of_constantinople",
        displayName: "Proclus of Constantinople",
        altNames: ["Proclus Constantinopolitanus"],
        birthplace: "Constantinople, Thrace, Roman Empire",
        deathplace: "Constantinople, Thrace, Eastern Roman Empire",
        lat: 41.008200,
        lon: 28.978400,
        imageUrl: 'https://images.weserv.nl/?url=media.pravoslavie.ru/279191.p.jpg?mtime=1512039708',
        fromYear: 385,
        fromApprox: true,
        toYear: 446,
        toApprox: false,
        camps: ["Eastern Father", "Greek", "Alexandrian"],
        mainCamp: "Alexandrian",
    },
    {
        pid: "nestorius_of_constantinople",
        displayName: "Nestorius of Constantinople",
        altNames: ["Nestorios"],
        birthplace: "Germanicia, Syria Euphratensis, Roman Empire",
        deathplace: "Thebaid, Aegyptus, Eastern Roman Empire",
        lat: 41.0082,
        lon: 28.9784,
        imageUrl: 'https://images.weserv.nl/?url=https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Nestorius_Hooghe_1688.png/960px-Nestorius_Hooghe_1688.png',
        fromYear: 386,
        fromApprox: true,
        toYear: 451,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Syriac*", "Antiochene", "Nestorian*"],
        mainCamp: "Nestorian*"
    },
    {
        pid: "julian_of_eclanum",
        displayName: "Julian of Eclanum",
        altNames: ["Julianus Eclanensis"],
        birthplace: "Unknown, Apulia et Calabria, Roman Empire",
        deathplace: "Unknown, Sicilia, Western Roman Empire",
        lat: 41.0262,
        lon: 15.0637,
        imageUrl: '',
        fromYear: 386,
        fromApprox: true,
        toYear: 455,
        toApprox: true,
        camps: ["Western Father", "Latin", "Pelagian"],
        mainCamp: "Pelagian"
    },
    {
        pid: "vincent_of_lerins",
        displayName: "Vincent of Lérins",
        altNames: ["Vincentius Lerinensis"],
        birthplace: "Toulouse, Gallia Narbonensis, Roman Empire",
        deathplace: "Lerina, Insulae Lero et Lerina, Western Roman Empire",
        lat: 43.50653899905318,
        lon: 7.047321380485845,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/2/21/Icon_of_St_Vincent_of_Lerins_by_Bojan_Teodosijevi%C4%87.jpg/960px-Icon_of_St_Vincent_of_Lerins_by_Bojan_Teodosijevi%C4%87.jpg',
        fromYear: 390,
        fromApprox: true,
        toYear: 445,
        toApprox: true,
        camps: ["Western Father", "Latin", "Nicene", "Massilian"],
        mainCamp: "Massilian"
    },
    {
        pid: "prosper_of_aquitaine",
        displayName: "Prosper of Aquitaine",
        altNames: ["Prosper Aquitanus", "Prosper Tiro"],
        birthplace: "Unknown, Gallia Aquitania, Roman Empire",
        deathplace: "Rome, Campania, Western Roman Empire",
        lat: 43.29846758926648,
        lon: 5.372771118291032,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/0/0f/Aquit%C3%A1niai_Szent_Prosper.jpg',
        fromYear: 390,
        fromApprox: true,
        toYear: 455,
        toApprox: true,
        camps: ["Western Father", "Latin", "Nicene", "Augustinian"],
        mainCamp: "Augustinian"
    },
    {
        pid: "patrick_of_armagh",
        displayName: "Patrick of Armagh",
        altNames: ["Saint Patrick", "Patricius", "Pátraic"],
        birthplace: "Banna Venta Berniae, Britannia, Roman Empire",
        deathplace: "Saul, Ulaid, Ireland",
        lat: 54.350278,
        lon: -6.652778,
        imageUrl: 'https://images.weserv.nl/?url=https://images.oca.org/icons/lg/march/0317patrick-ireland.jpg',
        fromYear: 390,
        fromApprox: true,
        toYear: 461,
        toApprox: true,
        camps: ["Western Father", "Latin", "Nicene", "Insular"],
        mainCamp: "Insular",
        authentic_works: [
            {text: "Confession", ital: true},
            {text: "Letter to the Soldiers of Coroticus", ital: true},
        ],
        disputed_works: [
            {text: "Sayings of Patrick", ital: true},
        ],
        pseudo_works: [
            {text: "Breastplate of Saint Patrick", ital: true, time: "8th cent. AD"},
            {text: "First Synod of Saint Patrick", ital: true, time: "~7th cent. AD"},
        ],
        works_about: [
            {text: "Book of the Angel", ital: true, time: "7th cent. AD"},
        ]
    },
    {
        pid: "leo_i_of_rome",
        displayName: "Leo I of Rome",
        altNames: ["Pope Leo I", "Leo the Great"],
        birthplace: "Unknown, Tuscia et Umbria, Roman Empire",
        deathplace: "Rome, Campania, Western Roman Empire",
        lat: 41.9028,
        lon: 12.4964,
        imageUrl: 'https://images.weserv.nl/?url=https://cdn.britannica.com/77/274177-050-4FECDDA0/Pope-Leo-I-the-Great-Saint-Leo-I.jpg',
        fromYear: 391,
        fromApprox: true,
        toYear: 461,
        toApprox: false,
        camps: ["Western Father", "Latin", "Chalcedonian"],
        mainCamp: "Chalcedonian"
    },
    {
        pid: "theodoret_of_cyrrhus",
        displayName: "Theodoret of Cyrrhus",
        altNames: ["Theodoret of Cyrus", "Theodoretus Cyrrhensis"],
        birthplace: "Antioch, Coele Syria, Roman Empire",
        deathplace: "Cyrrhus, Syria Prima, Eastern Roman Empire",
        lat: 36.744300,
        lon: 36.956600,
        imageUrl: 'https://images.weserv.nl/?url=www.shutterstock.com/editorial/image-editorial/OfTfkb06N5j6g3xbNTM3Mg==/theodoretus-386---457-bishop-cyrrhus-greek-1500w-9872518a.jpg',
        fromYear: 393,
        fromApprox: true,
        toYear: 458,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Syriac", "Antiochene", "Chalcedonian*"],
        mainCamp: "Antiochene",
    },
    {
        pid: "flavian_i_of_constantinople",
        displayName: "Flavian I of Constantinople",
        altNames: ["Flavian the Confessor", "Flavian the Martyr"],
        birthplace: "Unknown, Eastern Roman Empire",
        deathplace: "Hypaepa, Lydia, Eastern Roman Empire",
        lat: 41.0082,
        lon: 28.9784,
        imageUrl: 'https://images.weserv.nl/?url=https://handmadeiconsgreece.myshopify.com/cdn/shop/products/saint-flavian-patriarch-of-constantinople-icon.jpg?v=1681031588',
        fromYear: 400,
        fromApprox: true,
        toYear: 449,
        toApprox: false,
        camps: ["Eastern Father", "Greek", "Chalcedonian*"],
        mainCamp: "Chalcedonian*"
    },
    {
        pid: "dioscorus_i_of_alexandria",
        displayName: "Dioscorus I of Alexandria",
        altNames: ["Pope Dioscorus I", "Dioscorus the Great"],
        birthplace: "Unknown, Aegyptus, Eastern Roman Empire",
        deathplace: "Gangra, Paphlagonia, Eastern Roman Empire",
        lat: 31.2001,
        lon: 29.9187,
        imageUrl: 'https://images.weserv.nl/?url=https://polishmiaphysite.wordpress.com/wp-content/uploads/2021/08/dioscorus.jpg',
        fromYear: 400,
        fromApprox: true,
        toYear: 454,
        toApprox: false,
        camps: ["Eastern Father", "Greek", "Alexandrian", "Miaphysite"],
        mainCamp: "Miaphysite"
    },
    {
        pid: "ibas_of_edessa",
        displayName: "Ibas of Edessa",
        altNames: ["Ihiba of Edessa", "Hiba of Edessa"],
        birthplace: "Unknown, Syria, Eastern Roman Empire",
        deathplace: "Edessa, Osrhoene, Eastern Roman Empire",
        lat: 37.167400,
        lon: 38.795500,
        imageUrl: '',
        fromYear: 400,
        fromApprox: true,
        toYear: 457,
        camps: ["Eastern Father", "Syriac", "Greek", "Antiochene", "Chalcedonian"],
        mainCamp: "Antiochene",
    },
    {
        pid: "gennadius_i_of_constantinople",
        displayName: "Gennadius I of Constantinople",
        birthplace: "Unknown, Eastern Roman Empire",
        deathplace: "Constantinople, Thrace, Eastern Roman Empire",
        lat: 41.0082,
        lon: 28.9784,
        imageUrl: 'https://images.weserv.nl/?url=https://cdn.ballwool.com/products/1080_1440/0_1d271d1ab965e95a1d936c88309473be3f815e566a16644e860d6ad5b99daa0ba3109af4bbcafac06c8dcfb62ea1f94f274353288db8c1398389ccf97845ba43.webp',
        fromYear: 405,
        fromApprox: true,
        toYear: 471,
        toApprox: false,
        camps: ["Eastern Father", "Greek", "Antiochene", "Chalcedonian"],
        mainCamp: "Chalcedonian"
    },
    {
        pid: "timothy_ii_of_alexandria",
        displayName: "Timothy II of Alexandria",
        altNames: ["Timothy the Cat", "Timotheus Aelurus", "Timothy II Ailuros"],
        birthplace: "Alexandria, Aegyptus, Eastern Roman Empire",
        deathplace: "Alexandria, Aegyptus, Byzantine Empire",
        lat: 31.2001,
        lon: 29.9187,
        imageUrl: '',
        fromYear: 410,
        fromApprox: true,
        toYear: 477,
        toApprox: false,
        camps: ["Eastern Father", "Greek", "Syriac*", "Alexandrian", "Miaphysite"],
        mainCamp: "Miaphysite"
    },
    {
        pid: "faustus_of_riez",
        displayName: "Faustus of Riez",
        birthplace: "Britannia, Western Roman Empire",
        deathplace: "Reii, Gallia Narbonensis, Visigothic Kingdom",
        lat: 43.817388471307396,
        lon: 6.093818670359029,
        imageUrl: 'https://images.weserv.nl/?url=blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgQQOsEMlTr9eSzkGbPfg3SqWwrevYas3O2Ir7ui-RG5vYjWVteiPK1v6khWqzVbQgp-mv5x-uEAGefSUXJmsCmqvlpZrOS8b4wKBq9R_L0yYHz_FPqZ1xfzOmZ8e9PZl7SF2BskyrcFsc/s1600/Fauste+de+Riez-Ic%25C3%25B4ne.jpg',
        fromYear: 410,
        fromApprox: true,
        toYear: 490,
        toApprox: true,
        camps: ["Western Father", "Latin", "Nicene", "Massilian"],
        mainCamp: "Massilian"
    },
    {
        pid: "acacius_of_constantinople",
        displayName: "Acacius of Constantinople",
        birthplace: "Unknown, Eastern Roman Empire",
        deathplace: "Constantinople, Thrace, Byzantine Empire",
        lat: 41.0082,
        lon: 28.9784,
        imageUrl: '',
        fromYear: 420,
        fromApprox: true,
        toYear: 489,
        toApprox: false,
        camps: ["Eastern Father", "Greek", "Chalcedonian*"],
        mainCamp: "Chalcedonian*"
    },
    {
        pid: "peter_the_fuller",
        displayName: "Peter the Fuller",
        altNames: ["Peter Fullo", "Peter Cnapheus", "Peter II of Antioch"],
        birthplace: "Unknown, Eastern Roman Empire",
        deathplace: "Antioch, Syria Prima, Byzantine Empire",
        lat: 36.2021,
        lon: 36.1613,
        imageUrl: '',
        fromYear: 430,
        fromApprox: true,
        toYear: 488,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Miaphysite", "Monastic"],
        mainCamp: "Miaphysite"
    },
    {
        pid: "sabbas_the_sanctified",
        displayName: "Sabbas the Sanctified",
        altNames: ["Sabas the Sanctified", "Sabbas of Mar Saba", "Savvas the Sanctified"],
        birthplace: "Mutalaska, Cappadocia, Eastern Roman Empire",
        deathplace: "Mar Saba, Palaestina Prima, Byzantine Empire",
        lat: 31.704472,
        lon: 35.331583,
        imageUrl: 'https://images.weserv.nl/?url=https://cdn11.bigcommerce.com/s-30c33/images/stencil/1280x1280/products/3815/6065/StSavatheSanctifiedNewScrollSmall__76981.1668020939.jpg?c=2',
        fromYear: 439,
        fromApprox: true,
        toYear: 532,
        toApprox: false,
        camps: ["Eastern Father", "Greek", "Chalcedonian", "Monastic"],
        mainCamp: "Monastic"
    },
    {
        pid: "philoxenus_of_mabbug",
        displayName: "Philoxenus of Mabbug",
        altNames: ["Philoxenus of Hierapolis", "Xenaias", "Aksenaya"],
        birthplace: "Tahal, Beth Garmai, Sasanian Empire",
        deathplace: "Gangra, Paphlagonia, Byzantine Empire",
        lat: 36.5262,
        lon: 37.9564,
        imageUrl: 'https://images.weserv.nl/?url=https://upload.wikimedia.org/wikipedia/commons/2/2f/St._Philoxenus_of_Mabbug.jpg',
        fromYear: 440,
        fromApprox: true,
        toYear: 523,
        toApprox: false,
        camps: ["Eastern Father", "Syriac", "Greek", "Miaphysite"],
        mainCamp: "Miaphysite"
    },
    {
        pid: "avitus_of_vienne",
        displayName: "Avitus of Vienne",
        altNames: ["Alcimus Ecdicius Avitus"],
        birthplace: "Vienne, Viennensis, Western Roman Empire",
        deathplace: "Vienne, Viennensis, Burgundian Kingdom",
        lat: 45.5256,
        lon: 4.8743,
        imageUrl: 'https://images.weserv.nl/?url=https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgUL1AfXVqwbKofzZwGL0zvV0TbfFICfwcH1QuyMXDDS-StArEi-y8oiubbRX4EKQebVJy9AulOI2bGz9YVq76LsloF65cIF8PjoyOg79IF532eULIiGMahFTLyOcPwU3X3jTvks1IFRIFJ/s1600/avitus.jpg',
        fromYear: 450,
        fromApprox: true,
        toYear: 519,
        toApprox: true,
        camps: ["Western Father", "Latin", "Nicene", "Augustinian"],
        mainCamp: "Augustinian"
    },
    {
        pid: "jacob_of_sarug",
        displayName: "Jacob of Sarug",
        altNames: ["Jacob of Serugh", "Jacob of Serug", "Jacob of Batnae"],
        birthplace: "Kurtam, Osrhoene, Eastern Roman Empire",
        deathplace: "Batnan da-Srug, Osrhoene, Byzantine Empire",
        lat: 36.9761,
        lon: 38.4242,
        imageUrl: 'https://images.weserv.nl/?url=https://static.wixstatic.com/media/40f1c0_ae14f230697e45e7b43c89117033a240~mv2.jpg/v1/fill/w_700,h_1024,al_c,q_85,enc_avif,quality_auto/40f1c0_ae14f230697e45e7b43c89117033a240~mv2.jpg',
        fromYear: 451,
        fromApprox: true,
        toYear: 521,
        toApprox: false,
        camps: ["Eastern Father", "Syriac", "Miaphysite"],
        mainCamp: "Miaphysite"
    },
    {
        pid: "severus_of_antioch",
        displayName: "Severus of Antioch",
        altNames: ["Severus the Great", "Severus of Gaza"],
        birthplace: "Sozopolis, Pisidia, Eastern Roman Empire",
        deathplace: "Sakha, Aegyptus, Byzantine Empire",
        lat: 36.2021,
        lon: 36.1613,
        imageUrl: 'https://images.weserv.nl/?url=https://www.blessedmart.com/wp-content/uploads/2020/03/Saint-Severus-of-Antioch-Icon-Hand-Painted-Byzantine-Orthodox-2-38.jpg',
        fromYear: 459,
        fromApprox: true,
        toYear: 538,
        toApprox: false,
        camps: ["Eastern Father", "Greek", "Syriac*", "Miaphysite", "Monastic"],
        mainCamp: "Miaphysite"
    },
    {
        pid: "julian_of_halicarnassus",
        displayName: "Julian of Halicarnassus",
        altNames: ["Julian the Aphthartodocetist"],
        birthplace: "Unknown, Eastern Roman Empire",
        deathplace: "Unknown, Aegyptus, Byzantine Empire",
        lat: 37.0344,
        lon: 27.4305,
        imageUrl: '',
        fromYear: 465,
        fromApprox: true,
        toYear: 527,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Syriac*", "Miaphysite", "Eutychian*"],
        mainCamp: "Eutychian*"
    },
    {
        pid: "fulgentius_of_ruspe",
        displayName: "Fulgentius of Ruspe",
        altNames: ["Fabius Claudius Gordianus Fulgentius"],
        birthplace: "Thelepte, Byzacena, Vandal Kingdom",
        deathplace: "Ruspe, Byzacena, Vandal Kingdom",
        lat: 35.0330655265121,
        lon: 10.978028885092744,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/0/08/Fulgentius_von_Ruspe_17Jh.jpg/960px-Fulgentius_von_Ruspe_17Jh.jpg',
        fromYear: 467,
        fromApprox: true,
        toYear: 533,
        toApprox: true,
        camps: ["Western Father", "Latin", "Nicene", "Augustinian", "Monastic"],
        mainCamp: "Augustinian"
    },
    {
        pid: "caesarius_of_arles",
        displayName: "Caesarius of Arles",
        altNames: ["Caesarius Arelatensis", "Caesarius of Chalon"],
        birthplace: "Chalon-sur-Saône, Lugdunensis Prima, Western Roman Empire",
        deathplace: "Arles, Viennensis, Francia",
        lat: 43.676701,
        lon: 4.627800,
        imageUrl: 'https://images.weserv.nl/?url=i.pinimg.com/736x/5f/60/17/5f6017acda25823d2d962cb80cdcb16c.jpg',
        fromYear: 470,
        fromApprox: true,
        toYear: 543,
        toApprox: true,
        camps: ["Western Father", "Latin", "Nicene", "Augustinian", "Monastic"],
        mainCamp: "Augustinian",
    },
    {
        pid: "finnian_of_clonard",
        displayName: "Finnian of Clonard",
        altNames: ["Finnian mac Findloga", "Finnén of Clonard", "Vinnian"],
        birthplace: "Myshall, Laigin, Ireland",
        deathplace: "Clonard, Mide, Ireland",
        lat: 53.455,
        lon: -7.028,
        imageUrl: 'https://images.weserv.nl/?url=https://i.pinimg.com/736x/b7/62/09/b7620973694e491b703be94e51c7303b.jpg',
        fromYear: 470,
        fromApprox: true,
        toYear: 549,
        toApprox: true,
        camps: ["Western Father", "Latin", "Chalcedonian", "Monastic", "Insular"],
        mainCamp: "Monastic",
        disputed_works: [
            {text: "Penitential of Finnian", ital: true},
        ],
        works_about: [
            {text: "Life of Finnian", ital: true, time: "~12th cent. AD"},
        ]
    },
    {
        pid: "boethius",
        displayName: "Boethius",
        altNames: ["Anicius Manlius Severinus Boethius"],
        birthplace: "Rome, Campania, Kingdom of Odoacer",
        deathplace: "Pavia, Liguria, Ostrogothic Kingdom",
        lat: 45.192222,
        lon: 9.154722,
        imageUrl: 'https://images.weserv.nl/?url=https://upload.wikimedia.org/wikipedia/commons/0/0b/Boethius.jpeg?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original',
        fromYear: 480,
        fromApprox: true,
        toYear: 524,
        toApprox: true,
        camps: ["Western Father", "Latin", "Greek", "Chalcedonian", "Neoplatonist"],
        mainCamp: "Neoplatonist"
    },
    {
        pid: "brendan_of_clonfert",
        displayName: "Brendan of Clonfert",
        altNames: ["Brendan the Navigator", "Brénainn moccu Altai", "Brendan the Voyager"],
        birthplace: "Tralee, Mumu, Ireland",
        deathplace: "Annaghdown, Connachta, Ireland",
        lat: 53.241111,
        lon: -8.043611,
        imageUrl: 'https://images.weserv.nl/?url=https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIj_RM7OOncavzFG8Tf8--4l1NHHn9xt_1kRFT5RpYIN0q-PvEw0d_R-0&s=10',
        fromYear: 484,
        fromApprox: true,
        toYear: 577,
        toApprox: true,
        camps: ["Western Father", "Latin", "Chalcedonian", "Monastic", "Insular"],
        mainCamp: "Insular",
        pseudo_works: [
            {text: "Rule of Saint Brendan", ital: true},
        ],
        works_about: [
            {text: "The Voyage of Saint Brendan the Abbot", ital: true, time: "~8th cent. AD"},
            {text: "Life of Saint Brendan", ital: true, time: "~12th cent. AD"},
        ]
    },
    {
        pid: "leontius_of_jerusalem",
        displayName: "Leontius of Jerusalem",
        altNames: ["Leontios of Jerusalem", "Leontius Hierosolymitanus"],
        birthplace: "Unknown, Palaestina Prima, Byzantine Empire",
        deathplace: "Unknown, Palaestina Prima, Byzantine Empire",
        lat: 31.7784,
        lon: 35.2296,
        imageUrl: '',
        fromYear: 485,
        fromApprox: true,
        toYear: 543,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Chalcedonian", "Monastic"],
        mainCamp: "Chalcedonian"
    },
    {
        pid: "cassiodorus",
        displayName: "Cassiodorus",
        altNames: ["Flavius Magnus Aurelius Cassiodorus Senator"],
        birthplace: "Scylletium, Lucania et Bruttii, Kingdom of Odoacer",
        deathplace: "Vivarium, Lucania et Bruttii, Byzantine Empire",
        lat: 38.767778,
        lon: 16.569167,
        imageUrl: 'https://images.weserv.nl/?url=https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiyJOCUvhXsWbGTiTRhuLyDDA-HgNtf1hLWf6yNSVOIVAH9QTr9vqbaLEMonFxlb7ypclSplQSjZv3JQyhB8Eud2_QqgebW6DBXAWlm6LMMDt1N0IJYS2Ccxos5VdY3xIySIADMb0QNScU/s1600/Cassiodorus.jpg',
        fromYear: 485,
        fromApprox: true,
        toYear: 583,
        toApprox: true,
        camps: ["Western Father", "Latin", "Chalcedonian", "Monastic"],
        mainCamp: "Monastic"
    },
    {
        pid: "romanos_the_melodist",
        displayName: "Romanos the Melodist",
        altNames: ["Romanus the Melodist", "Roman the Melodist", "Romanos Melodos"],
        birthplace: "Emesa, Phoenice Libanensis, Byzantine Empire",
        deathplace: "Constantinople, Thrace, Byzantine Empire",
        lat: 41.0082,
        lon: 28.9784,
        imageUrl: 'https://images.weserv.nl/?url=https://www.saintromanos.org/images/IMG_2858.jpg',
        fromYear: 490,
        fromApprox: true,
        toYear: 556,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Syriac", "Chalcedonian"],
        mainCamp: "Chalcedonian"
    },
    {
        pid: "jacob_baradaeus",
        displayName: "Jacob Baradaeus",
        altNames: ["Jacob bar Addai", "Jacob bar Theophilus", "Jacob Burdoyo"],
        birthplace: "Tella, Osrhoene, Byzantine Empire",
        deathplace: "Maiuma, Palaestina Prima, Byzantine Empire",
        lat: 37.167403,
        lon: 38.795514,
        imageUrl: 'https://images.weserv.nl/?url=https://static.wikitide.net/orthodoxywiki/thumb/e/e2/Jacob_Baradaeus.jpg/300px-Jacob_Baradaeus.jpg',
        fromYear: 500,
        fromApprox: true,
        toYear: 578,
        toApprox: false,
        camps: ["Eastern Father", "Syriac", "Miaphysite", "Monastic"],
        mainCamp: "Miaphysite"
    },
    {
        pid: "eutychius_of_constantinople",
        displayName: "Eutychius of Constantinople",
        altNames: ["Eutychius of Theium"],
        birthplace: "Theium, Phrygia, Byzantine Empire",
        deathplace: "Constantinople, Thrace, Byzantine Empire",
        lat: 41.0082,
        lon: 28.9784,
        imageUrl: 'https://images.weserv.nl/?url=https://upload.wikimedia.org/wikipedia/commons/1/13/Eutychius_of_Constantinople.jpg',
        fromYear: 512,
        fromApprox: true,
        toYear: 582,
        toApprox: false,
        camps: ["Eastern Father", "Greek", "Chalcedonian"],
        mainCamp: "Chalcedonian"
    },
    {
        pid: "john_iv_of_constantinople",
        displayName: "John IV of Constantinople",
        altNames: ["John the Faster", "John Nesteutes", "John the Abstainer"],
        birthplace: "Constantinople, Thrace, Byzantine Empire",
        deathplace: "Constantinople, Thrace, Byzantine Empire",
        lat: 41.008583,
        lon: 28.980175,
        imageUrl: 'https://images.weserv.nl/?url=https://images.oca.org/icons/lg/september/0902johnfaster.jpg',
        fromYear: 530,
        fromApprox: true,
        toYear: 595,
        toApprox: false,
        camps: ["Eastern Father", "Greek", "Chalcedonian", "Monastic"],
        mainCamp: "Chalcedonian"
    },
    {
        pid: "gregory_i_of_rome",
        displayName: "Gregory I of Rome",
        altNames: ["Gregory the Great", "Pope Gregory I", "Gregory the Dialogist"],
        birthplace: "Rome, Campania, Byzantine Empire",
        deathplace: "Rome, Campania, Byzantine Empire",
        lat: 41.9028,
        lon: 12.4964,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7OTzRs2bKdaAJzSYqI2-UG1fCEiQ6b4iMDIoU746zR-NPG6Q06Tzk8y3b&s=10',
        fromYear: 540,
        fromApprox: true,
        toYear: 604,
        toApprox: false,
        camps: ["Western Father", "Latin", "Augustinian", "Chalcedonian", "Monastic"],
        mainCamp: "Chalcedonian"
    },
    {
        pid: "sophronius_i_of_jerusalem",
        displayName: "Sophronius I of Jerusalem",
        altNames: ["Sophronius the Sophist", "Sophronius the Wise"],
        birthplace: "Damascus, Phoenice Libanensis, Byzantine Empire",
        deathplace: "Jerusalem, Palaestina Prima, Rashidun Caliphate",
        lat: 31.778472,
        lon: 35.229611,
        imageUrl: 'https://images.weserv.nl/?url=https://upload.wikimedia.org/wikipedia/commons/e/e7/Athonite_Fresco_Icon_of_Saint_Sophronios_of_Jerusalem.jpg',
        fromYear: 560,
        fromApprox: true,
        toYear: 638,
        toApprox: false,
        camps: ["Eastern Father", "Greek", "Chalcedonian", "Dyothelite", "Monastic"],
        mainCamp: "Dyothelite"
    },
    {
        pid: "theodore_of_raithu",
        displayName: "Theodore of Raithu",
        altNames: ["Theodore of Pharan"],
        birthplace: "Unknown, Palaestina Tertia, Byzantine Empire",
        deathplace: "Unknown, Palaestina Tertia, Byzantine Empire",
        lat: 28.2417,
        lon: 33.6222,
        imageUrl: '',
        fromYear: 570,
        fromApprox: true,
        toYear: 625,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Chalcedonian", "Monastic"],
        mainCamp: "Chalcedonian"
    },
    {
        pid: "sergius_i_of_constantinople",
        displayName: "Sergius I of Constantinople",
        birthplace: "Unknown, Syria, Byzantine Empire",
        deathplace: "Constantinople, Thrace, Byzantine Empire",
        lat: 41.0082,
        lon: 28.9784,
        imageUrl: '',
        fromYear: 575,
        fromApprox: true,
        toYear: 638,
        toApprox: false,
        camps: ["Eastern Father", "Greek", "Monothelite"],
        mainCamp: "Monothelite"
    },
    {
        pid: "john_climacus",
        displayName: "John Climacus",
        altNames: ["John of the Ladder", "John of Sinai", "John the Sinaite", "John Scholasticus"],
        birthplace: "Unknown, Byzantine Empire",
        deathplace: "Mount Sinai, Misr, Rashidun Caliphate",
        lat: 28.555556,
        lon: 33.976111,
        imageUrl: 'https://cdn11.bigcommerce.com/s-30c33/images/stencil/500x659/products/4023/6646/John_of_the_Ladder3Small__10636.1709759143.jpg?c=2',
        fromYear: 579,
        fromApprox: true,
        toYear: 649,
        toApprox: true,
        camps: ["Eastern Father", "Greek", "Chalcedonian", "Monastic"],
        mainCamp: "Monastic",
        authentic_works: [
            {text: "The Ladder of Divine Ascent", ital: true},
            {text: "To the Shepherd", ital: true},
        ]
    },
    {
        pid: "maximus_the_confessor",
        displayName: "Maximus the Confessor",
        altNames: ["Maximus of Constantinople", "Maximus the Theologian"],
        birthplace: "Constantinople, Thrace, Byzantine Empire",
        deathplace: "Schemaris, Lazica, Byzantine Empire",
        lat: 41.025556,
        lon: 29.015278,
        imageUrl: 'https://images.weserv.nl/?url=https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjPdT-8fNKOGmr6SIC6tqMbwkww_yNJ9hdLxmDO36P0pW-m3GtMNT5FFH2bfMXYFMkm1UopvM8EVNfheujxYBmCLxFMAxRGHH_871CopJ_XxMyn01ROZUZjjKTsgqr-yxFUKovtQgl6xBjp/s1600/maximus2.jpg',
        fromYear: 580,
        fromApprox: true,
        toYear: 662,
        toApprox: false,
        camps: ["Eastern Father", "Greek", "Chalcedonian", "Dyothelite", "Neoplatonist", "Monastic"],
        mainCamp: "Dyothelite"
    },
    {
        pid: "martin_i_of_rome",
        displayName: "Martin I of Rome",
        altNames: ["Pope Martin I", "Martin the Confessor"],
        birthplace: "Todi, Umbria, Byzantine Empire",
        deathplace: "Cherson, Crimea, Byzantine Empire",
        lat: 41.885833,
        lon: 12.505833,
        imageUrl: 'https://images.weserv.nl/?url=https://thestationofthecross.com/wp-content/uploads/station-of-the-cross-saints-and-seasons-pope-saint-martin-i-the-first-scaled.jpg',
        fromYear: 590,
        fromApprox: true,
        toYear: 655,
        toApprox: false,
        camps: ["Western Father", "Latin", "Chalcedonian", "Dyothelite"],
        mainCamp: "Dyothelite"
    },
    {
        pid: "jacob_of_edessa",
        displayName: "Jacob of Edessa",
        altNames: ["James of Edessa", "Jacob of Urhoy"],
        birthplace: "Aindaba, Syria, Rashidun Caliphate",
        deathplace: "Tell Ada, Syria, Umayyad Caliphate",
        lat: 37.167403,
        lon: 38.795514,
        imageUrl: 'https://images.weserv.nl/?url=https://dss-syriacpatriarchate.org/wp-content/uploads/2025/07/%D9%8A%D8%B9%D9%82%D9%88%D8%A8-%D8%A7%D9%84%D8%B1%D9%87%D8%A7%D9%88%D9%8A-1.jpg',
        fromYear: 640,
        fromApprox: true,
        toYear: 708,
        toApprox: false,
        camps: ["Eastern Father", "Syriac", "Greek", "Miaphysite", "Monastic"],
        mainCamp: "Miaphysite"
    },
]