export type Person = {
    pid: string;
    displayName: string;
    altNames?: string[];
    birthplace?: string;
    deathplace?: string;
    lat: number;
    lon: number;
    imageUrl: string;
    fromYear: number;
    fromApprox?: boolean;
    toYear: number;
    toApprox?: boolean;
    camps: string[];
    mainCamp?: string;
}

export const all_persons: Person[] = [
    {
        pid: "peter_the_apostle",
        displayName: "Peter the Apostle",
        altNames: ["Simon Peter", "Cephas"],
        birthplace: "Bethsaida, Galilee, Judaea, Roman Empire",
        deathplace: "Rome, Italia, Roman Empire",
        lat: 32.91089391890956,
        lon: 35.63200492242213,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Saint_Peter-Sinai_%286th_Century%29_Crop.jpg/1024px-Saint_Peter-Sinai_%286th_Century%29_Crop.jpg',
        fromYear: -1,
        fromApprox: true,
        toYear: 65,
        toApprox: true,
        camps: ["Apostle"]
    },
    {
        pid: "matthew_the_apostle",
        displayName: "Matthew the Apostle",
        birthplace: "Capernaum, Galilee, Judaea, Roman Empire",
        deathplace: "Ethiopia or Persia",
        lat: 32.88,
        lon: 35.57,
        imageUrl: 'https://i0.wp.com/www.thebestcatholic.com/wp-content/uploads/2016/09/The-Best-Catholic.Matthew5a319b0c116995afb26cab5af9e51e4c.wix_mp_1024.jpeg',
        fromYear: 4,
        fromApprox: true,
        toYear: 68,
        toApprox: true,
        camps: ["Apostle"]
    },
    {
        pid: "james_the_just",
        displayName: "James the Just",
        birthplace: "Nazareth, Galilee, Judaea, Roman Empire",
        deathplace: "Jerusalem, Judaea, Roman Empire",
        lat: 32.70234804256465,
        lon: 35.297873906995605,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/9/96/Saint_James_the_Just.jpg',
        fromYear: 4,
        fromApprox: true,
        toYear: 62,
        toApprox: true,
        camps: ["Apostle"]
    },
    {
        pid: "paul_of_tarsus",
        displayName: "Paul of Tarsus",
        birthplace: "Tarsus, Cilicia, Roman Empire",
        deathplace: "Rome, Italia, Roman Empire",
        lat: 36.92,
        lon: 34.90,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/7/79/Giovanni_Francesco_Barbieri_-_Saint_Paul.jpg/960px-Giovanni_Francesco_Barbieri_-_Saint_Paul.jpg?20190309231900',
        fromYear: 5,
        fromApprox: true,
        toYear: 65,
        toApprox: true,
        camps: ["Apostle"]
    },
    {
        pid: "john_the_apostle",
        displayName: "John the Apostle",
        birthplace: "Bethsaida, Galilee, Judaea, Roman Empire",
        deathplace: "Ephesus, Ionia, Asia Minor, Roman Empire",
        lat: 32.91089391890956,
        lon: 35.63200492242213,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/7/79/Rubens_apostel_johannes_grt.jpg/1024px-Rubens_apostel_johannes_grt.jpg',
        fromYear: 6,
        fromApprox: true,
        toYear: 100,
        toApprox: true,
        camps: ["Apostle"]
    },
    {
        pid: "john_mark_the_evangelist",
        displayName: "John Mark the Evangelist",
        birthplace: "Cyrene, Cyrenaica, Roman Empire",
        deathplace: "Alexandria, Egypt, Roman Empire",
        lat: 32.819808224773865,
        lon: 21.859442918983255,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/9/92/Frans_Hals_085.jpg/1024px-Frans_Hals_085.jpg',
        fromYear: 7,
        fromApprox: true,
        toYear: 68,
        toApprox: true,
        camps: ["Apostle"]
    },
    {
        pid: "luke_the_evangelist",
        displayName: "Luke the Evangelist",
        birthplace: "Antioch, Syria, Roman Empire",
        deathplace: "Thebes, Boeotia, Achaia, Roman Empire",
        lat: 36.20405931892094,
        lon: 36.16216594217945,
        imageUrl: 'https://images.weserv.nl/?url=myocn.net/wp-content/uploads/2019/10/St-Luke-2.jpeg',
        fromYear: 10,
        fromApprox: true,
        toYear: 94,
        toApprox: true,
        camps: ["Apostle"]
    },
    {
        pid: "judas_thaddaeus",
        displayName: "Judas Thaddaeus",
        birthplace: "Galilee, Judaea, Roman Empire",
        deathplace: "",
        lat: 32.69903106070133,
        lon: 35.303823054325235,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/0/0d/Anthonis_van_Dyck%2C_Kunsthistorisches_Museum_Wien%2C_Gem%C3%A4ldegalerie_-_Apostel_Judas_Thadd%C3%A4us_-_GG_6809_-_Kunsthistorisches_Museum.jpg',
        fromYear: 10,
        fromApprox: true,
        toYear: 65,
        toApprox: true,
        camps: ["Apostle"]
    },
    {
        pid: "simon_magus",
        displayName: "Simon Magus",
        birthplace: "Gitta, Samaria, Judaea, Roman Empire",
        deathplace: "Rome, Italia, Roman Empire",
        lat: 32.275,
        lon: 35.190,
        imageUrl: 'https://images.weserv.nl/?url=miro.medium.com/v2/1*dtSfizyQhZ6dAVIujqL6FA.jpeg',
        fromYear: 15,
        fromApprox: true,
        toYear: 65,
        toApprox: true,
        camps: ["Gnostic"]
    },
    {
        pid: "clement_of_rome",
        displayName: "Clement of Rome",
        birthplace: "Rome, Italia, Roman Empire",
        deathplace: "Chersonesus, Crimea, Bosporan Kingdom, Roman Empire",
        lat: 41.88,
        lon: 12.59,
        imageUrl: 'https://lonelypilgrim.com/wp-content/uploads/2014/05/clement-of-rome.jpg?w=214',
        fromYear: 35,
        fromApprox: true,
        toYear: 101,
        toApprox: true,
        camps: ["Apostolic Father"]
    },
    {
        pid: "ignatius_of_antioch",
        displayName: "Ignatius of Antioch",
        birthplace: "Syria, Roman Empire",
        deathplace: "Rome, Italia, Roman Empire",
        lat: 36.204930647486165,
        lon: 36.16699792842562,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/b/bf/Hosios_Loukas_%28south_west_chapel%2C_south_side%29_-_Ignatios.jpg',
        fromYear: 45,
        fromApprox: true,
        toYear: 116,
        toApprox: true,
        camps: ["Apostolic Father"]
    },
    {
        pid: "papias_of_hierapolis",
        displayName: "Papias of Hierapolis",
        lat: 37.91,
        lon: 29.11,
        imageUrl: 'https://pbcdn1.podbean.com/imglogo/ep-logo/pbblog17411067/papias.jpeg',
        fromYear: 60,
        fromApprox: true,
        toYear: 130,
        toApprox: true,
        camps: ["Apostolic Father"]
    },
    {
        pid: "polycarp_of_smyrna",
        displayName: "Polycarp of Smyrna",
        birthplace: "Smyrna, Asia Minor, Roman Empire",
        deathplace: "Smyrna, Asia Minor, Roman Empire",
        lat: 38.42270378420375,
        lon: 27.14573543165261,
        imageUrl: 'https://images.weserv.nl/?url=orthodoxwiki.org/images/4/41/Polycarp.jpg',
        fromYear: 69,
        fromApprox: true,
        toYear: 155,
        toApprox: true,
        camps: ["Apostolic Father"]
    },
    {
        pid: "marcion_of_sinope",
        displayName: "Marcion of Sinope",
        birthplace: "Sinope, Pontus, Roman Empire",
        deathplace: "Rome, Italia, Roman Empire",
        lat: 42.02723141456593,
        lon: 35.151250446989664,
        imageUrl: "",
        fromYear: 85,
        fromApprox: true,
        toYear: 160,
        toApprox: true,
        camps: ["Gnostic"]
    },
    {
        pid: "justin_martyr",
        displayName: "Justin Martyr",
        birthplace: "Flavius Neapolis, Judaea, Roman Empire",
        deathplace: "Rome, Italia, Roman Empire",
        lat: 32.22230610198572,
        lon: 35.25856314446059,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/a/a7/Saint_Justin_Martyr_by_Theophanes_the_Cretan.jpg',
        fromYear: 100,
        fromApprox: true,
        toYear: 165,
        toApprox: true,
        camps: ["Eastern Father"]
    },
    {
        pid: "valentinus_gnostic",
        displayName: "Valentinus",
        lat: 41.88,
        lon: 12.59,
        imageUrl: 'https://bpb-us-e1.wpmucdn.com/blogs.uoregon.edu/dist/7/10891/files/2015/05/valentinus-1kiu29x.jpg',
        fromYear: 100,
        fromApprox: true,
        toYear: 180,
        toApprox: true,
        camps: ["Gnostic"]
    },
    {
        pid: "tatian_the_assyrian",
        displayName: "Tatian the Assyrian",
        altNames: ["Tatian the Syrian", "Tatian of Adiabene"],
        birthplace: "Assyria, Mesopotamia, Parthian Empire",
        deathplace: "Likely Syria or Mesopotamia",
        lat: 35.453997,
        lon: 43.257500,
        imageUrl: "https://images.weserv.nl/?url=images.squarespace-cdn.com/content/59714ce0cd39c3d2d282cc58/1500693415502-KN0XEXF712GJ1QNXTBVQ/tatian.jpg?content-type=image%2Fjpeg",
        fromYear: 120,
        fromApprox: true,
        toYear: 180,
        toApprox: true,
        camps: ["Eastern Father", "Gnostic"]
    },
    {
        pid: "theophilus_of_antioch",
        displayName: "Theophilus of Antioch",
        altNames: ["Theophilus of Antiochenus"],
        birthplace: "Near the Tigris and Euphrates rivers, Mesopotamia",
        deathplace: "Antioch, Syria, Roman Empire",
        lat: 36.20655,
        lon: 36.15722,
        imageUrl: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/1/16/Theophilus_Antiochenus.png/960px-Theophilus_Antiochenus.png",
        fromYear: 120,
        fromApprox: true,
        toYear: 183,
        toApprox: true,
        camps: ["Eastern Father"],
    },
    {
        pid: "irenaeus_of_lyon",
        displayName: "Irenaeus of Lyon",
        lat: 45.76,
        lon: 4.84,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/3/38/Saint_irenee_saint_irenee.jpg',
        fromYear: 125,
        fromApprox: true,
        toYear: 202,
        toApprox: true,
        camps: ["Western Father"]
    },
    {
        pid: "athenagoras_of_athens",
        displayName: "Athenagoras of Athens",
        altNames: ["Athenagoras the Athenian"],
        birthplace: "Athens, Achaia, Roman Empire",
        deathplace: "Unknown",
        lat: 37.9838,
        lon: 23.7275,
        imageUrl: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/6/62/Greek_Icon_of_Saint_Athenagoras_of_Athens.jpg/960px-Greek_Icon_of_Saint_Athenagoras_of_Athens.jpg",
        fromYear: 133,
        fromApprox: true,
        toYear: 190,
        toApprox: true,
        camps: ["Eastern Father"]
    },
    {
        pid: "clement_of_alexandria",
        displayName: "Clement of Alexandria",
        altNames: ["Titus Flavius Clemens"],
        birthplace: "Athens, Achaia, Roman Empire",
        deathplace: "Jerusalem, Syria Palaestina, Roman Empire",
        lat: 31.20025863903445,
        lon: 29.91846236548454,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Clement_alexandrin.jpg/500px-Clement_alexandrin.jpg',
        fromYear: 150,
        fromApprox: true,
        toYear: 215,
        toApprox: true,
        camps: ["Eastern Father", "Alexandrian"],
        mainCamp: "Eastern Father"
    },
    {
        pid: "tertullian_of_carthage",
        displayName: "Tertullian of Carthage",
        birthplace: "Carthage, Africa, Roman Empire",
        deathplace: "Carthage, Africa, Roman Empire",
        lat: 36.863945752812484,
        lon: 10.332574211900262,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/7/73/Tertullian2.png/1024px-Tertullian2.png',
        fromYear: 155,
        fromApprox: true,
        toYear: 220,
        toApprox: true,
        camps: ["Western Father", "Montanist"]
    },
    {
        pid: "hippolytus_of_rome",
        displayName: "Hippolytus of Rome",
        birthplace: "Rome, Italia, Roman Empire",
        deathplace: "Sardinia, Sardinia and Corsica, Roman Empire",
        lat: 41.88,
        lon: 12.59,
        imageUrl: 'https://images.weserv.nl/?url=images.oca.org/icons/lg/january/0130hippolytus.jpg',
        fromYear: 170,
        fromApprox: true,
        toYear: 236,
        toApprox: true,
        camps: ["Western Father"]
    },
    {
        pid: "alexander_of_jerusalem",
        displayName: "Alexander of Jerusalem",
        birthplace: "Unknown (Likely Cappadocia)",
        deathplace: "Caesarea Maritima, Syria Palaestina, Roman Empire",
        lat: 31.782201629960873,
        lon: 35.219051643225036,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/3/36/Alexander_of_Jerusalem.jpg',
        fromYear: 170,
        fromApprox: true,
        toYear: 251,
        toApprox: true,
        camps: ["Eastern Father"]
    },
    {
        pid: "origen_of_alexandria",
        displayName: "Origen of Alexandria",
        birthplace: "Alexandria, Egypt, Roman Empire",
        deathplace: "Tyre, Phoenice, Roman Empire",
        lat: 31.20025863903445,
        lon: 29.91846236548454,
        imageUrl: 'https://images.weserv.nl/?url=//upload.wikimedia.org/wikipedia/commons/thumb/2/20/Origen.jpg/960px-Origen.jpg',
        fromYear: 185,
        fromApprox: true,
        toYear: 253,
        toApprox: true,
        camps: ["Eastern Father", "Alexandrian", "Origenist"],
        mainCamp: "Origenist"
    },
    {
        pid: "cyprian_of_carthage",
        displayName: "Cyprian of Carthage",
        birthplace: "Carthage, Africa, Roman Empire",
        deathplace: "Carthage, Africa, Roman Empire",
        lat: 36.863945752812484,
        lon: 10.332574211900262,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/a/ae/Cyprian_von_Karthago2.jpg',
        fromYear: 210,
        fromApprox: true,
        toYear: 258,
        toApprox: true,
        camps: ["Western Father"]
    },
    {
        pid: "paul_of_thebes",
        displayName: "Paul of Thebes",
        birthplace: "Thebaid, Aegyptus, Roman Empire",
        deathplace: "Thebes, Aegyptus, Roman Empire",
        lat: 25.713133070514296,
        lon: 32.62190391281979,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/3/39/Paul_of_Thebes.jpg',
        fromYear: 227,
        fromApprox: true,
        toYear: 341,
        toApprox: true,
        camps: ["Eastern Father", "Monastic"],
        mainCamp: "Monastic"
    },
    {
        pid: "lucius_lactantius",
        displayName: "Lucius Lactantius",
        birthplace: "Unknown (Numidia)",
        deathplace: "Unknown",
        lat: 40.76770445285668,
        lon: 29.933262567556298,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/5/5c/Lactantius.jpg',
        fromYear: 250,
        fromApprox: true,
        toYear: 325,
        toApprox: true,
        camps: ["Western Father"]

    },
    {
        pid: "anthony_the_great",
        displayName: "Anthony the Great",
        birthplace: "Koma, Egypt, Roman Empire",
        deathplace: "Mount Colzim, Egypt, Roman Empire",
        lat: 29.299916177194383,
        lon: 31.169464033267953,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Saint_Anthony_%28Damaskinos%29.png/1024px-Saint_Anthony_%28Damaskinos%29.png',
        fromYear: 251,
        toYear: 356,
        camps: ["Eastern Father", "Monastic"],
        mainCamp: "Monastic"
    },
    {
        pid: "hosius_of_cordoba",
        displayName: "Hosius of Cordoba",
        altNames: ["Hosius the Confessor", "Osius", "Ossius"],
        birthplace: "Cordoba, Hispania, Roman Empire",
        deathplace: "Cordoba, Hispania, Roman Empire",
        lat: 37.88923549620351,
        lon: -4.779505534652193,
        imageUrl: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/0/05/Hosius_of_Cordoba.jpg/250px-Hosius_of_Cordoba.jpg",
        fromYear: 256,
        fromApprox: true,
        toYear: 359,
        toApprox: true,
        camps: ["Western Father", "Nicene"],
        mainCamp: "Nicene"
    },
    {
        pid: "arius_of_alexandria",
        displayName: "Arius of Alexandria",
        birthplace: "Ptolemais, Cyrenaica, Roman Empire",
        deathplace: "Constantinople, Thracia, Roman Empire",
        lat: 31.20025863903445,
        lon: 29.91846236548454,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/0/02/Arius_p%C3%BCsp%C3%B6k.jpg',
        fromYear: 256,
        fromApprox: true,
        toYear: 336,
        camps: ["Eastern Father", "Arian", "Alexandrian"],
        mainCamp: "Arian"
    },
    {
        pid: "alexander_i_of_alexandria",
        displayName: "Alexander I of Alexandria",
        birthplace: "Unknown",
        deathplace: "Alexandria, Egypt, Roman Empire",
        lat: 31.20025863903445,
        lon: 29.91846236548454,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/e/ec/Veljusa_Monastery_St._Alexander_of_Alexandria.jpg',
        fromYear: 260,
        fromApprox: true,
        toYear: 328,
        toApprox: true,
        camps: ["Eastern Father", "Nicene", "Alexandrian"],
        mainCamp: "Nicene"
    },
    {
        pid: "eusebius_of_caesarea",
        displayName: "Eusebius of Caesarea",
        altNames: ["Eusebius Pamphilius"],
        birthplace: "Caesarea Maritima, Syria Palaestina, Roman Empire",
        deathplace: "Caesarea Maritima, Syria Palaestina, Roman Empire",
        lat: 32.51667524676977,
        lon: 34.9019981388087,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/7/70/Eusebius_of_Caesarea_Rabbula_Gospels_Icon.jpg',
        fromYear: 260,
        fromApprox: true,
        toYear: 339,
        camps: ["Eastern Father", "Origenist"],
        mainCamp: "Origenist"
    },
    {
        pid: "eusebius_of_nicomedia",
        displayName: "Eusebius of Nicomedia",
        birthplace: "Unknown",
        deathplace: "Constantinople, Thracia, Roman Empire",
        lat: 40.76247630958466,
        lon: 29.917517499562084,
        imageUrl: 'https://images.weserv.nl/?url=',
        fromYear: 280,
        fromApprox: true,
        toYear: 341,
        camps: ["Eastern Father", "Arian"],
        mainCamp: "Arian"
    },
    {
        pid: "hilarion_of_gaza",
        displayName: "Hilarion of Gaza",
        altNames: ["Hilarion the Great", "Hilarion of Thavata"],
        birthplace: "Thavata, Syria Palaestina, Roman Empire",
        deathplace: "Cyprus, Roman Empire",
        lat: 31.516648470299234,
        lon: 34.44998533044062,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/9/9f/Hilarion_the_Great_%28Menologion_of_Basil_II%29_%28cropped%29.jpg',
        fromYear: 291,
        fromApprox: true,
        toYear: 371,
        toApprox: true,
        camps: ["Eastern Father", "Monastic"],
        mainCamp: "Monastic"
    },
    {
        pid: "athanasius_of_alexandria",
        displayName: "Athanasius of Alexandria",
        birthplace: "Alexandria, Egypt, Roman Empire",
        deathplace: "Alexandria, Egypt, Roman Empire",
        lat: 31.20025863903445,
        lon: 29.91846236548454,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/2/26/Ikone_Athanasius_von_Alexandria.jpg',
        fromYear: 296,
        fromApprox: true,
        toYear: 373,
        camps: ["Eastern Father", "Nicene", "Alexandrian"],
        mainCamp: "Nicene"
    },
    {
        pid: "hilary_of_poitiers",
        displayName: "Hilary of Poitiers",
        birthplace: "Pictavium, Gallia Aquitania, Roman Empire",
        deathplace: "Pictavium, Septem Provinciae, Roman Empire",
        lat: 46.579841096591224,
        lon: 0.3416894346137863,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/0/06/Hilary_of_Poitiers.png/500px-Hilary_of_Poitiers.png',
        fromYear: 310,
        fromApprox: true,
        toYear: 367,
        toApprox: true,
        camps: ["Western Father", "Nicene"],
        mainCamp: "Nicene"
    },
    {
        pid: "didymus_the_blind",
        displayName: "Didymus the Blind",
        birthplace: "Unknown, probably Alexandria",
        deathplace: "Unknown, probably Alexandria",
        lat: 31.20025863903445,
        lon: 29.91846236548454,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/4/46/Didymus_the_blind.jpg',
        fromYear: 313,
        fromApprox: true,
        toYear: 398,
        toApprox: true,
        camps: ["Eastern Father", "Alexandrian", "Origenist", "Nicene"],
        mainCamp: "Origenist"
    },
    {
        pid: "cyril_of_jerusalem",
        displayName: "Cyril of Jerusalem",
        altNames: ["Cyrillus Hierosolymitanus"],
        birthplace: "Jerusalem, Syria Palaestina, Roman Empire",
        deathplace: "Jerusalem, Palaestina Prima, Roman Empire",
        lat: 31.77889,
        lon: 35.22556,
        imageUrl: 'https://images.weserv.nl/?url=adoremus.org/app/uploads/2020/03/StCyril-5.jpg',
        fromYear: 315,
        fromApprox: true,
        toYear: 386,
        toApprox: true,
        camps: ["Eastern Father", "Nicene"],
        mainCamp: "Nicene"
    },
    {
        pid: "epiphanius_of_salamis",
        displayName: "Epiphanius of Salamis",
        birthplace: "Besanduk, Syria Palaestina, Roman Empire",
        deathplace: "at sea near Cyprus",
        lat: 35.1865222055156,
        lon: 33.90346888919054,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/2/2c/Epiphanius-Kosovo.jpg',
        fromYear: 315,
        fromApprox: true,
        toYear: 403,
        camps: ["Eastern Father", "Nicene", "Iconoclast"],
        mainCamp: "Nicene"
    },
    {
        pid: "gregory_of_nazianzus",
        displayName: "Gregory of Nazianzus",
        altNames: ["Gregory Nazianzen"],
        birthplace: "Arianzus, Cappadocia, Roman Empire",
        deathplace: "Arianzus, Cappadocia, Roman Empire",
        lat: 38.26143964360644,
        lon: 34.38466113638501,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/5/5d/Gregor-Chora_%28cropped%29.jpg',
        fromYear: 329,
        fromApprox: true,
        toYear: 390,
        toApprox: true,
        camps: ["Eastern Father", "Nicene", "Cappadocian Father"],
        mainCamp: "Cappadocian Father"
    },
    {
        pid: "basil_of_caesarea",
        displayName: "Basil of Caesarea",
        altNames: ["Basil the Great"],
        birthplace: "Caesarea Mazaca, Cappadocia, Roman Empire",
        deathplace: "Caesarea Mazaca, Cappadocia, Roman Empire",
        lat: 38.722417611256404,
        lon: 35.48746598237236,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/0/04/Basil_of_Caesarea.jpg',
        fromYear: 330,
        fromApprox: true,
        toYear: 379,
        camps: ["Eastern Father", "Nicene", "Cappadocian Father", "Monastic"],
        mainCamp: "Cappadocian Father"
    },
    {
        pid: "gregory_of_nyssa",
        displayName: "Gregory of Nyssa",
        altNames: ["Gregory Nyssen"],
        birthplace: "Neocaesarea, Cappadocia, Roman Empire",
        deathplace: "Nyssa, Cappadocia, Roman Empire",
        lat: 38.93386362845272,
        lon: 33.94907023316791,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/2/29/Gregory_of_Nyssa.jpg',
        fromYear: 335,
        fromApprox: true,
        toYear: 394,
        toApprox: true,
        camps: ["Eastern Father", "Nicene", "Cappadocian Father", "Origenist"],
        mainCamp: "Cappadocian Father"
    },
    {
        pid: "ambrose_of_milan",
        displayName: "Ambrose of Milan",
        altNames: ["Aurelius Ambrosius"],
        birthplace: "Augusta Treverorum, Gallia Belgica, Roman Empire",
        deathplace: "Mediolanum, Italia, Western Roman Empire",
        lat: 45.46509212922207,
        lon: 9.18057778962911,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/7/74/AmbroseOfMilan_%28cropped%29.jpg',
        fromYear: 339,
        fromApprox: true,
        toYear: 397,
        camps: ["Western Father", "Nicene"],
        mainCamp: "Nicene"
    },
    {
        pid: "jerome_of_stridon",
        displayName: "Jerome of Stridon",
        birthplace: "Stridon, Dalmatia, Roman Empire",
        deathplace: "Bethlehem, Palaestina, Byzantine Empire",
        lat: 44.2,
        lon: 17.7,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/5/5f/MatthiasStom-SaintJerome-Nantes.jpg',
        fromYear: 342,
        fromApprox: true,
        toYear: 420,
        camps: ["Western Father", "Eastern Father", "Nicene", "Monastic"],
        mainCamp: "Nicene"
    },
    {
        pid: "rufinus_of_aquileia",
        displayName: "Rufinus of Aquileia",
        lat: 45.767206596249956,
        lon: 13.368906699413515,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/1/10/Rufinus_Aquileiensis.jpg/800px-Rufinus_Aquileiensis.jpg',
        fromYear: 344,
        fromApprox: true,
        toYear: 411,
        toApprox: true,
        camps: ["Western Father", "Origenist"],
        mainCamp: "Origenist"
    },
    {
        pid: "john_chrysostom",
        displayName: "John Chrysostom",
        altNames: ["John of Antioch", "John of Constantinople"],
        lat: 41.00817513927148,
        lon: 28.978539039041394,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/c/cf/Johnchrysostom.jpg',
        fromYear: 349,
        fromApprox: true,
        toYear: 407,
        camps: ["Eastern Father", "Nicene", "Antiochene"],
        mainCamp: "Nicene"
    },
    {
        pid: "augustine_of_hippo",
        displayName: "Augustine of Hippo",
        altNames: ["Aurelius Augustinus", "Austin"],
        birthplace: "Thagaste, Numidia Cirtensis, Roman Empire",
        deathplace: "Hippo Regius, Numidia Cirtensis, Western Roman Empire",
        lat: 36.90,
        lon: 7.75,
        imageUrl: 'https://images.fineartamerica.com/images/artworkimages/mediumlarge/3/saint-augustine-of-hippo-philippe-de-champaigne-war-is-hell-store.jpg',
        fromYear: 354,
        toYear: 430,
        camps: ["Western Father", "Nicene", "Augustinian", "Monastic"],
        mainCamp: "Augustinian"
    },
    {
        pid: "pelagius_pelagian",
        displayName: "Pelagius",
        altNames: ["Pelagius the Monk", "Pelagius Brito"],
        birthplace: "Probably Britain, Roman Empire",
        deathplace: "Possibly Palestine",
        lat: 52.4153,
        lon: -3.4821,
        imageUrl: 'https://images.weserv.nl/?url=https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Pelagius.jpg/960px-Pelagius.jpg',
        fromYear: 354,
        fromApprox: true,
        toYear: 418,
        toApprox: true,
        camps: ["Western Father", "Pelagian", "Monastic"],
        mainCamp: "Pelagian"
    },
    {
        pid: "john_cassian",
        displayName: "John Cassian",
        altNames: ["John the Ascetic", "John Cassian the Roman"],
        birthplace: "Scythia Minor, Roman Empire",
        deathplace: "Massalia, Gallia Narbonensis, Western Roman Empire",
        lat: 43.30270514648704,
        lon: 5.36823823706311,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/a/a0/John_Cassian.jpeg/960px-John_Cassian.jpeg',
        fromYear: 360,
        fromApprox: true,
        toYear: 435,
        toApprox: true,
        camps: ["Western Father", "Eastern Father", "Nicene", "Semipelagian", "Monastic"],
        mainCamp: "Semipelagian"
    },
    {
        pid: "caelestius_pelagian",
        displayName: "Caelestius",
        altNames: ["Celestius"],
        birthplace: "Probably Italy, Western Roman Empire",
        deathplace: "Unknown; perhaps Constantinople, Thracia, Eastern Roman Empire",
        lat: 41.9028,
        lon: 12.4964,
        imageUrl: "",
        fromYear: 380,
        fromApprox: true,
        toYear: 430,
        toApprox: true,
        camps: ["Western Father", "Pelagian"],
        mainCamp: "Pelagian"
    },
    {
        pid: "prosper_of_aquitaine",
        displayName: "Prosper of Aquitaine",
        altNames: ["Prosper Aquitanus", "Prosper Tiro"],
        birthplace: "Gallia Aquitania, Roman Empire",
        deathplace: "Rome, Italia, Western Roman Empire",
        lat: 43.29846758926648,
        lon: 5.372771118291032,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/0/0f/Aquit%C3%A1niai_Szent_Prosper.jpg',
        fromYear: 390,
        fromApprox: true,
        toYear: 455,
        toApprox: true,
        camps: ["Western Father", "Nicene", "Augustinian"],
        mainCamp: "Augustinian"
    },
    {
        pid: "vincent_of_lerins",
        displayName: "Vincent of Lérins",
        altNames: ["Vincentius Lerinensis"],
        birthplace: "Toulouse, Gallia Narbonensis, Roman Empire",
        deathplace: "Lerina, Insulae Lero et Lerina, Western Roman Empire",
        lat: 43.50653899905318,
        lon: 7.047321380485845,
        imageUrl: 'https://images.weserv.nl/?url=https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Icon_of_St_Vincent_of_Lerins_by_Bojan_Teodosijevi%C4%87.jpg/960px-Icon_of_St_Vincent_of_Lerins_by_Bojan_Teodosijevi%C4%87.jpg',
        fromYear: 390,
        fromApprox: true,
        toYear: 445,
        toApprox: true,
        camps: ["Western Father", "Nicene", "Semipelagian"],
        mainCamp: "Semipelagian"
    },
    {
        pid: "faustus_of_riez",
        displayName: "Faustus of Riez",
        birthplace: "Brittania, Western Roman Empire",
        deathplace: "Reii, Gallia Narbonensis, Western Roman Empire",
        lat: 43.817388471307396,
        lon: 6.093818670359029,
        imageUrl: 'https://images.weserv.nl/?url=blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgQQOsEMlTr9eSzkGbPfg3SqWwrevYas3O2Ir7ui-RG5vYjWVteiPK1v6khWqzVbQgp-mv5x-uEAGefSUXJmsCmqvlpZrOS8b4wKBq9R_L0yYHz_FPqZ1xfzOmZ8e9PZl7SF2BskyrcFsc/s1600/Fauste+de+Riez-Ic%25C3%25B4ne.jpg',
        fromYear: 400,
        fromApprox: true,
        toYear: 490,
        toApprox: true,
        camps: ["Western Father", "Nicene", "Semipelagian"],
        mainCamp: "Semipelagian"
    },
    {
        pid: "avitus_of_vienne",
        displayName: "Avitus of Vienne",
        altNames: ["Alcimus Ecdicius Avitus"],
        birthplace: "Vienne, Viennensis, Western Roman Empire",
        deathplace: "Vienne, Burgundian Kingdom",
        lat: 45.5256,
        lon: 4.8743,
        imageUrl: "https://images.weserv.nl/?url=https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgUL1AfXVqwbKofzZwGL0zvV0TbfFICfwcH1QuyMXDDS-StArEi-y8oiubbRX4EKQebVJy9AulOI2bGz9YVq76LsloF65cIF8PjoyOg79IF532eULIiGMahFTLyOcPwU3X3jTvks1IFRIFJ/s1600/avitus.jpg",
        fromYear: 450,
        fromApprox: true,
        toYear: 519,
        toApprox: true,
        camps: ["Western Father", "Nicene", "Augustinian"],
        mainCamp: "Augustinian"
    },
    {
        pid: "fulgentius_of_ruspe",
        displayName: "Fulgentius of Ruspe",
        altNames: ["Fabius Claudius Gordianus Fulgentius"],
        birthplace: "Thelepte, Byzacena, Vandal Kingdom",
        deathplace: "Ruspe, Byzacena, Vandal Kingdom",
        lat: 35.0330655265121,
        lon: 10.978028885092744,
        imageUrl: 'https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/0/08/Fulgentius_von_Ruspe_17Jh.jpg/960px-Fulgentius_von_Ruspe_17Jh.jpg',
        fromYear: 467,
        fromApprox: true,
        toYear: 533,
        toApprox: true,
        camps: ["Western Father", "Nicene", "Augustinian", "Monastic"],
        mainCamp: "Augustinian"
    },
    {
        pid: "caesarius_of_arles",
        displayName: "Caesarius of Arles",
        altNames: ["Caesarius Arelatensis", "Caesarius of Chalon"],
        birthplace: "Chalon-sur-Saône, Lugdunensis Prima, Western Roman Empire",
        deathplace: "Arles, Viennensis, Francia",
        lat: 43.676701,
        lon: 4.627800,
        imageUrl: 'https://images.weserv.nl/?url=i.pinimg.com/736x/5f/60/17/5f6017acda25823d2d962cb80cdcb16c.jpg',
        fromYear: 470,
        fromApprox: true,
        toYear: 543,
        toApprox: true,
        camps: ["Western Father", "Nicene", "Augustinian", "Monastic"],
        mainCamp: "Augustinian",
    }
]